### ISSUE TITLE
LAG and HOST fields

### ISSUE THREAD

**Issue by duylong** [obsidiandynamics/kafdrop#1]
Hi,

Can we integrate the LAG and HOST informations for each partition ? For example, we can easily see the blocking hosts.

**Comment by ekoutanov** [comment]
Per-partition lag is something that's definitely useful and something we lack at the moment. But getting current host information isn't trivial, and the host-partition assignment is ephemeral and subject to change on each rebalancing.

**Comment by ekoutanov** [comment]
Release 3.7.0 now has per-partition consumer lag support

**Comment by adivardhan** [comment]
@ekoutanov Is the release 3.7.0 merged into master (does master have Comsumer lag support?) ?

**Comment by ekoutanov** [comment]
@adivardhan Yes, it's in master.

**Comment by adivardhan** [comment]
@ekoutanov  Thanks! I got it after commenting. My bad.
Also, any plan to include alerts (email notifier, etc) as a module?
