### ISSUE TITLE
Unintentionally topic creation

### ISSUE THREAD

**Issue by IndeedSi** [obsidiandynamics/kafdrop#100]
Hi, Kafdrop is a really great tool. I have been using it for a while and forked a version for my protobuf2 usage.
One problem I find is that sometime topic got created unintentionally. Further digging into the issue, when you navigate to `/topic/{name}` or `/topic/{name}/message`, and if the topic doesn't exist, it will be created automatically (if the broker turns auto-creation on). 
After reading [this blog](https://www.techpoolx.com/blog/the-side-effect-of-fetching-kafka-topic-metadata.html), I think the problem is we are using `KafkaConsumer#partitionsFor(String topic)`. Can we use listTopics to check first instead?

**Comment by ekoutanov** [comment]
It may seem annoying, but the issue has nothing to do with Kafdrop, but with your broker configuration. You need to disable topic auto-create by setting `auto.create.topics.enable=false` on the broker. This is also a recommended setting for production deployments.

**Comment by IndeedSi** [comment]
@ekoutanov  It's mainly for our local development and QA environment. Usually we only set `auto.create.topics.enable=false` in production. Even for your docker-compose Kafka image, it will also enable auto create topics...
Would you take some time to look at the PR? It's pretty small change https://github.com/obsidiandynamics/kafdrop/pull/101/files
