### ISSUE TITLE
Question: Topic Messages - Additional size field that excludes control messages?

### ISSUE THREAD

**Issue by rognorak** [obsidiandynamics/kafdrop#104]
When using Kafka Streams or anything that supports transaction markers, there are control messages written into user topics.  In this case, looking at user topics, the size and offsets show totals including the control messages.

Is it possible / would it be useful to add an additional size field that omits control messages, so we can see how many user messages are available in a topic ?

Thanks -

**Comment by ekoutanov** [comment]
While it is technically possible, it is an expensive operation involving a full topic scan, and therefore will unlikely be implemented. Kafka does not reveal the true size of the topic, which may include not only control messages, but also messages that have been rolled back. All we know is the difference between the low-water mark and the high-water mark, and may approximate the size of the topic.
