### ISSUE TITLE
Kafdrop got 504 Gateway Time-out when one of broker offline

### ISSUE THREAD

**Issue by SpeedEX** [obsidiandynamics/kafdrop#110]
In past couple days I happen to get hand in Kafka cluster upgrading and had found that during rolling update period, the Kafdrop UI will get the 504 Gateway Time-out error until the rolling update is completed. 
Is this behaviour expected or not ? Are any configurations (either on Kafdrop itself or on Kafka) needed to prevent it ? 

P.S. Also, the Kafdrop will show same error (504) after doing partition reassignment on some big topics and I needed to manually rolling restart the brokers to made the kafdrop back to normal.

**Comment by ekoutanov** [comment]
What do the logs look like when this happens?

**Comment by SpeedEX** [comment]
> What do the logs look like when this happens?

Sorry for late reply. 
Unfortunately, the log is gone since it pass the retention period already.
I will post the log when it happens again.
