### ISSUE TITLE
Could we add kafka test container to project

### ISSUE THREAD

**Issue by nicklester** [obsidiandynamics/kafdrop#111]
When working on my previous PR I had to stand up my own kafka cluster in docker to properly test changes. Could we add a test container to the project, onto which we can start to add test cases? Any other suggestions? Happy to implement

**Comment by ekoutanov** [comment]
There's a docker-compose setup at the moment in `docker-compose/kafka-kafdrop` that runs the latest images of kafka and kafdrop; not really for testing, but more for getting started.

Happy for you to have a crack at a test container if you like. It could be quite useful.

**Comment by ekoutanov** [comment]
There's a docker-compose setup at the moment in `docker-compose/kafka-kafdrop` that runs the latest images of kafka and kafdrop; not really for testing, but more for getting started.

Happy for you to have a crack at a test container if you like. It could be quite useful.

**Comment by nicklester** [comment]
Actually, maybe thinking of using something like embedded kafka to allow us to bring up a single node cluster, write to topics and ensure that the client code in kafdrop works nicely after changes are made. I guess it's just a start..

**Comment by ekoutanov** [comment]
Are you thinking of using some sort of browser based testing like Selenium to drive the client? It would certainly be a _very_ nice thing to have.
