### ISSUE TITLE
Viewing topic messages with empty Type name shows NPE stacktrace on the screen

### ISSUE THREAD

**Issue by shantanualsi** [obsidiandynamics/kafdrop#112]
1. Go to the Topic messages screen of any topic
2. Select message format as PROTOBUF and keep the type name empty
3. Click View Messages button

Actual behavior: A full stack trace of Null Pointer Exception is thrown on the screen
Expected behavior: Should ask the user to  format and not show a stacktrace on the UI

**Comment by ekoutanov** [comment]
That should hopefully be resolved thanks to @aaronwolmutt .

@shantanualsi can you please confirm fix and close issue.

**Comment by shantanualsi** [comment]
Cool.. I see now I get a message to select the descriptor file.. 
Thanks!
