### ISSUE TITLE
Connect to SSL Heroku broker

### ISSUE THREAD

**Issue by santiagomoneta** [obsidiandynamics/kafdrop#117]
Hello, I hope you can help me... I'm trying to connect to a broker I have hosted in Heroku (that requires SSL) and I followed some of the guidelines to connect using SSL but in all cases, the docker container starts, and shutdown quickly... I ended up making a movie so I can see the error and all I can see is that it fails to load the keystone... this is what I did:

 I cloned this repo and from the terminal, on the project;'s folder, I created a **kafka.properties** file with this content:

```
security.protocol=SSL
ssl.endpoint.identification.algorithm=
ssl.protocol=TLS
ssl.key.password=mule123
ssl.keystore.location=/Users/smoneta/kafka.client.keystore.jks
ssl.keystore.password=mule123
ssl.keystore.type=JKS
ssl.truststore.location=/Users/smoneta/kafka.client.truststore.jks
ssl.truststore.password=mule123
ssl.truststore.type=JKS
```
Note: The above config works with "CONDUKTOR"

I save that and I run this command:

```
docker run -d --rm -p 9000:9000  -e KAFKA_BROKERCONNECT=ec2-3-220-121-33.compute-1.amazonaws.com:9096,ec2-3-234-75-100.compute-1.amazonaws.com:9096,ec2-3-227-129-191.compute-1.amazonaws.com:9096,ec2-3-208-232-40.compute-1.amazonaws.com:9096,ec2-100-25-107-37.compute-1.amazonaws.com:9096,ec2-35-168-34-44.compute-1.amazonaws.com:9096,ec2-100-24-239-47.compute-1.amazonaws.com:9096,ec2-3-231-110-127.compute-1.amazonaws.com:9096  -e KAFKA_PROPERTIES=$(cat kafka.properties | base64)  obsidiandynamics/kafdrop :latest
```

[Here](https://drive.google.com/file/d/1-mnVQYoXJuXUG_8FL6s_1De_i_x7-uMq/view?usp=sharing) is a video of it

**Comment by ekoutanov** [comment]
How are you passing in the keystore and truststore files? It wasn't in the environment variables to the container, and you don't seem to have mounted a volume. There are examples in the README on how to configure these.

**Comment by santiagomoneta** [comment]
Thanks I will try that!
