### ISSUE TITLE
Configuration of client consumers

### ISSUE THREAD

**Issue by andreu30** [obsidiandynamics/kafdrop#119]
Hello I'm using KafDrop since some weeks and noticed that offsets are not reset when I stop KafDrop for a couple of hours (offsets.retention.minutes=60). When restarting KafDrop the offsets are at their previous levels for all topics. From documentation it is stated that KafDrop holds a pool of client consumers to inspect the topic messages. But I don't see options to configure the consumers from KafDrop. On the other hand KafDrop consumers cannot be found using "kafka-consumer-groups.sh" script. What am I missing here?

**Comment by ekoutanov** [comment]
Kafdrop does not user a consumer group. Consequently, there are no committed offsets.

**Comment by andreu30** [comment]
OK so offsets will raise to infinite unless topics are getting cleared / deleted. Is there still a way to reset offets in KafDrop?

**Comment by ekoutanov** [comment]
I'm not sure I understand what you mean? Kafdrop does not commit offsets. (Unless there's a bug that I'm not aware of.)

Can you show a screenshot which shows offsets that are a result of Kafdrop?

**Comment by andreu30** [comment]
Yeah sure. Here you see for the topic "mysql-requestatus" an offset of over 70.000. No consumer-groups are listed for the broker using "kafka-consumer-groups.sh" command.
![KafDropScreenshot](https://user-images.githubusercontent.com/35791656/81097084-ab515a80-8f07-11ea-93e8-7de68e026120.PNG)

**Comment by andreu30** [comment]
Maybe I'm too stupid but the offsets are increasing and are not being reset. The topic is fed by a Kafka source connector polling a MySQL database. But I think that's not relevant here.

**Comment by andreu30** [comment]
Now I get it. After restarting KafDrop running the jar the consumer config show up stating a consumer group id of NULL. This is the reason why it cannot be deleted or offsets reset. When starting the KafDrop.jar it is possible to change these default parameters? Or is there some properties file?

auto.commit.interval.ms = 5000
auto.offset.reset = latest
bootstrap.servers = [localhost:9092]
check.crcs = true
client.dns.lookup = default
client.id = 
connections.max.idle.ms = 540000
default.api.timeout.ms = 60000
enable.auto.commit = true
exclude.internal.topics = true
fetch.max.bytes = 52428800
fetch.max.wait.ms = 500
fetch.min.bytes = 1
group.id = null
heartbeat.interval.ms = 3000
interceptor.classes = []
internal.leave.group.on.close = true
isolation.level = read_uncommitted
key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
max.partition.fetch.bytes = 1048576
max.poll.interval.ms = 300000
max.poll.records = 500
metadata.max.age.ms = 300000
metric.reporters = []
metrics.num.samples = 2
metrics.recording.level = INFO
metrics.sample.window.ms = 30000
partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
receive.buffer.bytes = 65536
reconnect.backoff.max.ms = 1000
reconnect.backoff.ms = 50
request.timeout.ms = 30000
retry.backoff.ms = 100
sasl.client.callback.handler.class = null
sasl.jaas.config = null
sasl.kerberos.kinit.cmd = /usr/bin/kinit
sasl.kerberos.min.time.before.relogin = 60000
sasl.kerberos.service.name = null
sasl.kerberos.ticket.renew.jitter = 0.05
sasl.kerberos.ticket.renew.window.factor = 0.8
sasl.login.callback.handler.class = null
sasl.login.class = null
sasl.login.refresh.buffer.seconds = 300
sasl.login.refresh.min.period.seconds = 60
sasl.login.refresh.window.factor = 0.8
sasl.login.refresh.window.jitter = 0.05
sasl.mechanism = GSSAPI
security.protocol = PLAINTEXT
send.buffer.bytes = 131072
session.timeout.ms = 10000
ssl.cipher.suites = null
ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
ssl.endpoint.identification.algorithm = https
ssl.key.password = null
ssl.keymanager.algorithm = SunX509
ssl.keystore.location = null
ssl.keystore.password = null
ssl.keystore.type = JKS
ssl.protocol = TLS
ssl.provider = null
ssl.secure.random.implementation = null
ssl.trustmanager.algorithm = PKIX
ssl.truststore.location = null
ssl.truststore.password = null
ssl.truststore.type = JKS
value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

**Comment by ekoutanov** [comment]
I'm going to close this as it does not make sense to me. And I'm guessing it doesn't make sense to others as there have been no comments.
