### ISSUE TITLE
Configurable of default partition number and Replication factor when creating a new topic

### ISSUE THREAD

**Issue by SpeedEX** [obsidiandynamics/kafdrop#123]
This screen capture is from the new topic UI and I would like to change the default number show here. I know I can change it before clicking create button but it would be nice if I can change those values.

![image](https://user-images.githubusercontent.com/8520185/81300244-98728d80-90a1-11ea-9c3c-b17652a14e49.png)

**Comment by ekoutanov** [comment]
Are you essentially saying that you would like application-level defaults for 'number of partitions' and 'replication factor'?

**Comment by SpeedEX** [comment]
> Are you essentially saying that you would like application-level defaults for 'number of partitions' and 'replication factor'?

Yes. I know it sound like an unnecessary feature but it would be nice to have it.

Edit: Also, I would like to know how the UI get and show those number as well if I can change that value instead.

**Comment by ekoutanov** [comment]
Do you want to give this a crack?
