### ISSUE TITLE
SSL Authentication failed when running with docker

### ISSUE THREAD

**Issue by marcelobp** [obsidiandynamics/kafdrop#124]
Hi all,

Trying to run the docker image with ssl, however facing the following issue when application starts:

`2020-05-08 10:51:05.315  WARN 14 [| kafdrop-admin] o.a.k.c.NetworkClient                    : [AdminClient clientId=kafdrop-admin] Connection to node -1 (brokerurl/brokerip:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.`

**Command line executed:**
`winpty docker run -it -p 9000:9000 -e KAFKA_BROKERCONNECT=brokerurl:9092 -e KAFKA_PROPERTIES="$(cat ssl.properties | base64)" -e KAFKA_TRUSTSTORE="$(cat keystore.jks | base64)" -e KAFKA_KEYSTORE="$(cat truststore.jks | base64)" obsidiandynamics/kafdrop`

**Properties as follows:**
```
security.protocol=SSL
ssl.truststore.password=test1234
ssl.keystore.password=test1234
ssl.key.password=test1234
ssl.keystore.type=JKS
ssl.truststore.type=JKS
```

**Comment by spacenorden** [comment]
Hi Marcel,
how were you able to resolve the issue? I'm facing the same message with security.protocol=SASL_SSL...
Thanks!

**Comment by marcelobp** [comment]
Hi spacenorden,
The issue was related to my JKS and it is working now. Please let me know if I can help you somehow.
Thanks
