### ISSUE TITLE
how to view latest message instead of first message within a topic?

### ISSUE THREAD

**Issue by lovelyplanet2019** [obsidiandynamics/kafdrop#130]
i just installed Kafdrop.
On view message, the first message is displayed.

Does sorting supported?

how to view latest message instead of first message within a topic?

**Comment by Wouter86** [comment]
It is supported in my pull request, just wait for it to be accepted or directly checkout my fork...
Messages can be read from "any" partition instead of a specific one, and in that case the messages are ordered by descending timestamp.

**Comment by qkdreyer** [comment]
Bump, looking forward this feature
