### ISSUE TITLE
Would it be possible to run the application without the Delete actions enabled?

### ISSUE THREAD

**Issue by marcelobp** [obsidiandynamics/kafdrop#131]
Hi all,

I am running KafDrop in my company and would like to people use it only as a monitoring tool. For that, it would be great if I can run the application without some actions, as for example the Delete Topic button.

Is there any way to run the application like that?

Regards,
Marcelo

**Comment by svaranasi-corporate** [comment]
I would love to know about this, too. We're also looking to use this tool for monitoring only, and would like to turn off all modifications to the cluster.

**Comment by ghost** [comment]
I'd suggest taking a fork of the project and redeploying the project only with what features you need.

**Comment by svaranasi-corporate** [comment]
CMAK has this ability to enable/disable features. You can disable modifications to the topic, if you'd like. 

https://github.com/yahoo/CMAK#configuration

`application.features=["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]`

It would be nice to have something like that in KafDrop without having to fork code.

**Comment by marcelobp** [comment]
> CMAK has this ability to enable/disable features. You can disable modifications to the topic, if you'd like.
> 
> https://github.com/yahoo/CMAK#configuration
> 
> `application.features=["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]`
> 
> It would be nice to have something like that in KafDrop without having to fork code.

Is it possible to view the ACLs and topics messages on CMAK ?

**Comment by Wouter86** [comment]
I fixed this in my pull request. Wait for it to be accepted or get my fork and hide the delete topic button with the kafdrop command (see readme.md).

**Comment by ekoutanov** [comment]
Resolved in #136
