### ISSUE TITLE
org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support LIST_OFFSETS with version in range [2,5]. The supported range is [0,1].

### ISSUE THREAD

**Issue by OracleGao** [obsidiandynamics/kafdrop#134]
org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support LIST_OFFSETS with version in range [2,5]. The supported range is [0,1].

**Comment by OracleGao** [comment]
how to fix this exception

**Comment by ghost** [comment]
What version of Kafka are you using? Can you please post a stack trace and more details about the incident.

**Comment by ekoutanov** [comment]
Sounds like this is pre version 1.0
