### ISSUE TITLE
How to set topic.deleteEnabled with Docker?

### ISSUE THREAD

**Issue by marcelobp** [obsidiandynamics/kafdrop#138]
Hi all,

@Wouter86 Could you please let me know how to set `topic.deleteEnabled` in case I am running Kafdrop with Docker?

Cheers,
Marcelo

**Comment by Wouter86** [comment]
Hi Marcelo,

You can try adding the following parameter to your docker run command:
`-e CMD_ARGS="--topic.deleteEnabled=false"`

If it works, it would be a good idea to add the 'CMD_ARGS' info to the documentation on [Docker Hub](https://hub.docker.com/r/obsidiandynamics/kafdrop).

**Comment by marcelobp** [comment]
Hi @Wouter86,

Thanks for your response and for adding the new feature where we can disable delete action.
CMD_ARGS has worked fine with the docker run command.

Cheers,
Marcelo
