### ISSUE TITLE
Not Found A 404 error has occurred: Not Found

### ISSUE THREAD

**Issue by jedaan** [obsidiandynamics/kafdrop#140]
Hi, 
My docker-compose.yml 

version: "2"
  services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

when navigating to localhost:9000, I'm got 
![Screenshot from 2020-06-02 12-26-35](https://user-images.githubusercontent.com/5883725/83503818-55eb7780-a4cc-11ea-98b3-f7f22f73c592.png)

**Comment by ekoutanov** [comment]
Can you confirm this still an issue in 3.27.0?
