### ISSUE TITLE
kafdrop on k8s is not working after last commit

### ISSUE THREAD

**Issue by danilorsilva** [obsidiandynamics/kafdrop#141]
I have been using kafdrop successfully, but i try to install today and receive this error:

Error: template: kafdrop/templates/deployment.yaml:94:14: executing "kafdrop/templates/deployment.yaml" at <.Values.mountProtoDesc.enabled>: nil pointer evaluating interface {}.enabled

Thanks!

**Comment by danilorsilva** [comment]
Now, you MUST "--set mountProtoDesc.enabled=(true or false)", otherwise the installation using helm will not works.

**Comment by danilorsilva** [comment]
Keep not working, they install but not working. CrashLoopBackOff

**Comment by danilorsilva** [comment]
I removed all the new lines on deployment.yaml

https://github.com/obsidiandynamics/kafdrop/commit/7454a49b3d0e1b45f4080c709b92e781665d15f2

and it works.

I will keep this issue opened waiting for a official solution.

**Comment by ekoutanov** [comment]
@danilorsilva are you able to provide a PR with a fix?

**Comment by jonathan-mothership** [comment]
@ekoutanov fixed in #149

**Comment by ekoutanov** [comment]
Thanks @jonathan-mothership
