### ISSUE TITLE
If any User login, RBAC is in pipeline as an enhancement?

### ISSUE THREAD

**Issue by adivardhan** [obsidiandynamics/kafdrop#15]
Currently do we have user login for Kafdrop? If yes, how are we persisting user credentials?
If not, then is there any plan to provide this feature as an enhancement?

**Comment by ekoutanov** [comment]
Nothing specific at this stage.

Current recommendation is to secure access using a reverse proxy layer above Kafdrop, for example HTTPD, NGINX or an API Gateway of some sort. (There is an example in `README.md` that shows how basic auth can be used with NGINX.)

**Comment by adivardhan** [comment]
Okay. Thanks for update.
