### ISSUE TITLE
Resouce files e.g. CSS not found because of relative path

### ISSUE THREAD

**Issue by dweber019** [obsidiandynamics/kafdrop#150]
In the current docker image the path for the resource files like CSS are relative and therefore can't be found. This happens as sone as I navigate to a sub route as seen in the error.

Error: `http://localhost:9000/topic/<topic name>/css/bootstrap.min.css`

Version: `docker pull obsidiandynamics/kafdrop:3.26.0`

I think this commit caused the issue https://github.com/obsidiandynamics/kafdrop/commit/d693864e382a7b43bbe38431ff0a9f8c23e26f4e

**Comment by ekoutanov** [comment]
@FrozenInc can you please take a look?

**Comment by psykidellic** [comment]
Yeah, this is a bummer. I upgraded to latest because --topic.createEnabled=false was not working in previous version so I tried to upgrade. This is a regression I believe.

**Comment by ohjongsung** [comment]
I had the same problem.
![error_default_servlet_contextpath](https://user-images.githubusercontent.com/17442438/84729671-3e81b380-afcf-11ea-973e-abed5a867219.PNG)

When setting server.servlet.contextPath also causes problems main view.
![error_custom_servlet_contextpath](https://user-images.githubusercontent.com/17442438/84729996-fe6f0080-afcf-11ea-8421-4a81befada47.PNG)

So if I roll back the commit d693864 it works fine.

**Comment by ekoutanov** [comment]
For the time being, reverted the commit in master.

**Comment by psykidellic** [comment]
~~Hi, is there any official docker image I can use/try?~~

Looks like 3.26.0 was updated with it. I can confirm everything works now.

**Comment by RohitJones** [comment]
The 3.26.0 (tried the official docker image) is still broken on the topic overview page.

**Comment by ekoutanov** [comment]
Can you check latest 3.27.0. Should be working now.

**Comment by RohitJones** [comment]
@ekoutanov Yup, the UI is now working as intended. Thank you for the fix !
