### ISSUE TITLE
Add the message count for each topic in overview page

### ISSUE THREAD

**Issue by aaabidunique** [obsidiandynamics/kafdrop#154]
In overview page it would be helpful to see the message count of the topic i.e available message count and total message count.
It will help us to check how many message are currently present after expiry in some cases also.

**Comment by ekoutanov** [comment]
This capability is not supported by Kafka. There is no way of knowing the quantity of records in a topic, or even in a single partition (short of reading through the entire topic).

**Comment by aaabidunique** [comment]
Thanks for the update.
@ekoutanov available size and total size of a topic which is in TopicVO is what I was looking for.
Could we add that stat in the overview?
I could do a PR if you would like.
