### ISSUE TITLE
TimeoutException: Timed out waiting for a node assignment

### ISSUE THREAD

**Issue by jdwebsphere** [obsidiandynamics/kafdrop#155]
Hi, Getting below error when we connect to AWS MSK with TLS enabled. Can you check and suggest me what's wrong with this setting? Is there anything wrong with this configs? Not sure why the connection gets timed out.

Here is the kafkaclient.properties & docker compose file.

version: "2"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9002:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafkha-b1:9095,kafkha-b3:9095,kafkha-b2:9095"
      KAFKA_PROPERTIES: "(cat /opt/ssl/kafka.properties | base64)"
      KAFKA_KEYSTORE: "(cat /opt/ssl/kafka.client.keystore.jks | base64)"
      KAFKA_TRUSTSTORE: "(cat /opt/ssl/kafka.client.truststore.jks | base64)"

security.protocol=SSL
ssl.endpoint.identification.algorithm=
ssl.protocol=TLS
ssl.key.password=*********
ssl.keystore.location=/opt/ssl/kafka.client.keystore.jks
ssl.keystore.password=********
ssl.keystore.type=JKS
ssl.truststore.location=/opt/kafka.client.truststore.jks
ssl.truststore.type=JKS

**Comment by jdwebsphere** [comment]
![image](https://user-images.githubusercontent.com/39145725/85805298-c7e86280-b700-11ea-8515-4ae09f3ad55b.png)

**Comment by ekoutanov** [comment]
If you're passing the keystore/truststore content via an environment variable (base64-encoded), then you should't specify the `.location` properties, just the passwords.

Also, if you have a problem connecting via Kafdrop, try connecting first via the command-line clients that are shipped with Kafka to make sure you have the configuration right.

**Comment by jdwebsphere** [comment]
Yeah it is working when I connect from command line to list it out. 

 bin/kafka-topics.sh --list --zookeeper

**Comment by jdwebsphere** [comment]
Also I removed the keystore/truststore location from properties file as it is defined in docker compose environments. Is there anything missing? Not sure why it is timing out

**Comment by jdwebsphere** [comment]
_s there a problem with cert file formats?

kafdrop_1  | 2020-06-25 23:36:13.230  WARN 1 [           main] o.a.k.c.c.AbstractConfig                 : The configuration 'ssl.truststore.location' was supplied but isn't a known config.
kafdrop_1  | 2020-06-25 23:36:13.231  WARN 1 [           main] o.a.k.c.c.AbstractConfig                 : The configuration 'ssl.keystore.location' was supplied but isn't a known config.
kafdrop_1  | 2020-06-25 23:36:13.231  WARN 1 [           main] o.a.k.c.c.AbstractConfig                 : The configuration '��m�F����_�i���)z�bz�ڱ�' was supplied but isn't a known config.


kafdrop_1 | Writing Kafka properties into kafka.properties
kafdrop_1 | Writing Kafka truststore into kafka.truststore.jks
kafdrop_1 | base64: invalid input
kafdrop_1 | Writing Kafka keystore into kafka.keystore.jks
kafdrop_1 | base64: invalid input

**Comment by jdwebsphere** [comment]
kafdrop_1  | Writing Kafka properties into kafka.properties
kafdrop_1  | Writing Kafka truststore into kafka.truststore.jks
kafdrop_1  | base64: invalid input
kafdrop_1  | Writing Kafka keystore into kafka.keystore.jks
kafdrop_1  | base64: invalid input

**Comment by jaizquierdogalan** [comment]
First of all thanks for the help @jdwebsphere and @ekoutanov, I wonder if the issue was resolved .
Currently I have had the same problem :( with a similar stack:

- AWS MSK

- AWS EKS

- Terraform with EKS and AWS providers

My configMap:
`resource "kubernetes_config_map" "msk-tls-auth" {
  metadata {
    name = "msk-tls-auth"
    namespace = "msk"
  }

  data = {
    "kafka.client.keystore.jks"        = "${filebase64("${path.module}/files/tls/kafka.client.keystore.jks")}"
    "kafka.client.keystore.password"   = xxxxxxxxx
    "kafka.client.truststore.jks"      = "${filebase64("${path.module}/files/tls/kafka.client.truststore.jks")}"
    "kafka.client.truststore.password" = xxxxxxxxx
    "kafka.properties"                 = "${filebase64("${path.module}/files/properties/kafka.properties")}"
  }

}
`
My kafka.properties:
`security.protocol=SSL
ssl.protocol=TLS
ssl.key.password=xxxxxxxxx
ssl.keystore.password=xxxxxxxxx
ssl.keystore.type=JKS
ssl.truststore.type=JKS`

My EKS deployment:

`
resource "kubernetes_deployment" "kafka-kafdrop" {
  metadata {
    name = "kafka-kafdrop"
    namespace = "msk"
    labels = {
      app = "kafka-kafdrop"
    }
  }

  spec {
    replicas = 1
    
    selector {
      match_labels = {
        app = "kafka-kafdrop"
      }
    }

    template {
      metadata {
        labels = {
          app = "kafka-kafdrop"
        }
      }
      spec {
        container {
          image = "obsidiandynamics/kafdrop"
          name  = "kafka-kafdrop"
          port {
            container_port  = "9000"
          }

          env {
            name  = "KAFKA_BROKERCONNECT"
            value = var.brokers
          }

          # env {
          #   name  = "KAFKA_PROPERTIES"
          #   value = "/tmp/kafka.client.keystore.jks"
          # }

          env {
            name  = "KAFKA_KEYSTORE"
            value = "/tmp/files/kafka.client.keystore.jks"
          }

          env {
            name  = "KAFKA_TRUSTSTORE"
            value = "/tmp/files/kafka.client.truststore.jks"
          }

          env {
            name  = "KAFKA_PROPERTIES"
            value = "/tmp/files/kafka.properties"
          }

          # env {
          #   name  = "JVM_OPTS"
          #   value = "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"       
          # }

          volume_mount {
            name = "msk-tls-auth"
            mount_path = "/tmp/files/"
            read_only  = false
          }
 
          resources {
            limits {
              cpu    = "2000m"
              memory = "4024Mi"
            }
            requests {
              cpu    = "125m"
              memory = "50Mi"
            }
          }
        }
        volume {
            name = "msk-tls-auth"
            config_map {
              name = "msk-tls-auth"
            }
        }
      }
    }
  }
}

resource "kubernetes_service" "kafka-kafdrop" {
  metadata {
    name = "kafka-kafdrop"
    namespace = "msk"
  }
  spec {
    selector = {
      app = "kafka-kafdrop"
    }
    external_name = "kafka-kafdrop"
    port {
      port        = 80
      target_port = 9000
    }

    type = "ClusterIP"

  }
}

resource "kubernetes_ingress" "kafka-kafdrop" {
  metadata {
    name        = "kafka-kafdrop"
    namespace   = "msk"
    annotations = {
      "cert-manager.io/cluster-issuer": "dapda-tls-acme-prod-v0.15.0-nginx-nlb"
      "kubernetes.io/ingress.class" : "nginx-nlb"
    }
  }

  spec {
    backend {
      service_name = "kafka-kafdrop"
      service_port = 80
    }

    rule {
      host         = var.domain
      http {
        path {
          backend {
            service_name = "kafka-kafdrop"
            service_port = 80
          }
        }
      }
    }

    tls {
      hosts       = [var.domain]
      secret_name = "kafdrop-tls"
    }
  }
}

resource "aws_route53_record" "kafka-kafdrop" {
  zone_id = var.zone_id
  name    = var.name
  type    = "CNAME"
  ttl     = "300"
  records = [var.domain]
}
`
Has anyone the same problem?

**Comment by ekoutanov** [comment]
```
   env {
        name  = "KAFKA_KEYSTORE"
        value = "/tmp/files/kafka.client.keystore.jks"
      }
```

The value should be the base64-encoded contents of the keystore.

**Comment by jaizquierdogalan** [comment]
I tried that but If I put content encode to base64 I receive:
`standard_init_linux.go:211: exec user process caused "argument list too long"                                                                                                                                                      │
│ stream closed    `

Argument list too long

Thanks @ekoutanov

**Comment by ekoutanov** [comment]
perhaps you have too many entries in your keystore or truststore? Just make sure that your keystores have only the keys and certs necessary to connect to the Kafka cluster, and nothing else.

Otherwise you would have to access them as a mounted volume

**Comment by stephaneuh** [comment]
Hi, same issue for me. I'm able to use kafka-console-consumer/producer.sh with no problem. But I get this "Timed out waiting for a node assignment" error when I try to use the same config file with Kafdrop:

```
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="xxxxxxxxxxx" \
  password="xxxxxxxxxxx";
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
ssl.truststore.location=trust.jks
ssl.truststore.password=xxxxxx
ssl.endpoint.identification.algorithm=
```
On the kafka side we can see this exception:
```
SSLEngine.closeInBound() raised an exception.
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1667)
[SocketServer brokerId=1] Failed authentication with ip-xxxxxxxxxxxxx (SSL handshake failed)
```
Thanks,

**Comment by sonac** [comment]
Ran into the same issue myself, was able to fix it by providing only `security.protocol=SSL` in `kafka.properties` file and no truststore at all (since by default you don't create any certs in MSK, just enable passing only of TLS encrypted traffic).
So in my case isntallation command was: `helm upgrade -i kafdrop chart --set kafka.properties="$(cat kafka.properties | base64)"` and that's it

**Comment by cyberjso** [comment]
> Ran into the same issue myself, was able to fix it by providing only `security.protocol=SSL` in `kafka.properties` file and no truststore at all (since by default you don't create any certs in MSK, just enable passing only of TLS encrypted traffic).
> So in my case isntallation command was: `helm upgrade -i kafdrop chart --set kafka.properties="$(cat kafka.properties | base64)"` and that's it

I'm running into the same issue. The scenario on my case is similar, I have an MK cluster with TLS enabled. Even after following @sonac  suggestion (setting SSL enabled on kafka.properties file only and loading It into the runtime as and encoded Env var) the error remains. 

Are there any progress on that once the issue is still open?

**Comment by jgrammen-agilitypr** [comment]
The following configuration worked for me:
In the systemd unit file for kafdrop:
Environment=KAFKA_BROKERCONNECT=hostanme:port,hostname2:port,host3:port
Environment=KAFKA_PROPERTIES_FILE=/opt/kafka.properties

/opt/kafka.properties contains:
security.protocol=SSL
