### ISSUE TITLE
Kafdrop UI integration failed to open up the page

### ISSUE THREAD

**Issue by manee2k6** [obsidiandynamics/kafdrop#158]
Here is the configuration used to integrate kafdrop to bring more flexibility of kafka topic ui and CMAK. Please help on this issue, did i miss any here to have this ui up and running. My suspect here is on the env variables used. I have zookeeper tools and kafka-schema registry, kakfa rest api and kafka manager. With this i am trying to bring this UI to make life easier in term of view of brokers, topic, browse message. Pls help
kafdrop-ui:
    image: obsidiandynamics/kafdrop
    networks:
      - internal
      - traefik-net
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest:8082"
      PROXY: "true"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://xxxxxxxxxxxx:12209"
        tag: "kafdrop-ui"
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:xxxxxxxxxxx"
        - "traefik.frontend.whiteList.useXForwardedFor=true"
        - "traefik.port=9001"
        - "traefik.enable=true"
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 500M
          cpus: '0.50'
        reservations:
          cpus: '0.1'
          memory: 100M

**Comment by lfmunoz** [comment]
Shows logs. Do "docker ps", find the container id, then do "docker logs containerId"

I.e,. the following would mean you cannot connect to the kafka broker:
```
2020-10-06 16:46:02.418  WARN 1 [| kafdrop-admin] o.a.k.c.NetworkClient                    : [AdminClient clientId=kafdrop-admin] Connection to node -1 (localhost/127.0.0
.1:9092) could not be established. Broker may not be available.
```
