### ISSUE TITLE
Multiple cluster monitoring (2 separate Kafka-Zookeeper ecosystem) possible? 

### ISSUE THREAD

**Issue by adivardhan** [obsidiandynamics/kafdrop#16]
Is it possible to monitor 2 different Kafka-Zookeeper ecosystem?

I have 5 Broker-3 Zookeeper, running as one ecosystem.
I also have another ecosystem with 7 Broker-3 Zookeeper.

Is it possible to monitor them both?

**Comment by ekoutanov** [comment]
In the present state — no. You would have to spin up two separate Kafdrop instances to do that (which is actually pretty easy to do).

In the future, we might have a configurable list of clusters, but this isn't a priority. Having said that, if you're willing to submit a PR, it would be most welcome.
