### ISSUE TITLE
No messages found in partition

### ISSUE THREAD

**Issue by evgygor** [obsidiandynamics/kafdrop#162]
Docker obsidiandynamics/kafdrop:3.27.0 
Kafka security SASL_SSL

In 80% of  getting messages from the topic requests, the following message appears:

"No messages found in partition..."

**The request:**
http://localhost:9000/topic/testtopic/messages?partition=0&offset=0&count=100&keyFormat=DEFAULT&format=DEFAULT

**Log in the docker:**
`2020-07-14 12:59:27.797  INFO 604 [ XNIO-1 task-16] nfiguration$ProtobufDescriptorProperties : No descriptor folder configured, skip the setting!!
errorAtts: {timestamp=Tue Jul 14 12:59:28 GMT 2020, status=404, error=Not Found, message=Not Found, path=/js/bootstrap.min.js.map}
 `
**Log in  the browser:**
`DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for http://localhost:9000/js/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
popper.min.js:4 Uncaught SyntaxError: Unexpected token 'export'
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for http://localhost:9000/js/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
messages?partition=0&offset=0&count=100&keyFormat=DEFAULT&format=DEFAULT:92 Uncaught TypeError: Cannot read property 'setAttribute' of null
    at restyle (messages?partition=0&offset=0&count=100&keyFormat=DEFAULT&format=DEFAULT:92)
    at messages?partition=0&offset=0&count=100&keyFormat=DEFAULT&format=DEFAULT:82
restyle @ messages?partition=0&offset=0&count=100&keyFormat=DEFAULT&format=DEFAULT:92
(anonymous) @ messages?partition=0&offset=0&count=100&keyFormat=DEFAULT&format=DEFAULT:82
setTimeout (async)
(anonymous) @ messages?partition=0&offset=0&count=100&keyFormat=DEFAULT&format=DEFAULT:82
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
`

**Comment by akeadey** [comment]
Here is more information about this error...
https://stackoverflow.com/questions/46459767/popper-js-in-bootstrap-4-gives-syntaxerror-unexpected-token-export
