### ISSUE TITLE
Add possibility to set the custom cluster name

### ISSUE THREAD

**Issue by evgygor** [obsidiandynamics/kafdrop#169]
It would be nice to get the parameter for configuring the cluster name and display this parameter
in the near or above the "Kafka Cluster Overview" title
For example the environment variable:
KAFKA_CLUSTER_NAME="My dev cluster"

Thanks

**Comment by togacaptain** [comment]
Was just looking for this functionality. Would be nice when moving between environment to be able to tell at a glance which one I'm looking at.
