### ISSUE TITLE
Kafdrop error 500 when some broker from the cluster is down

### ISSUE THREAD

**Issue by mtm41** [obsidiandynamics/kafdrop#173]
Hi. I have an environment with 3 kafka brokers properly configured as brokerConnect's parameter. Indeed, I am able to see it on the web UI. But, when one of the three kafka broker is down the kardrop web is unreachable, after waiting for 2 minutes It displays a 500 error code. We thought that the web UI should be able to keep showing the distribution of charge between the others two nodes. Am I wrong?

Thanks in advance.

**Comment by mtm41** [comment]
I downgraded to version 3.0.0 and the error is gone. On the other hand, the error appear since version 3.25.0 until 3.9.0, apparently.

**Comment by ghost** [comment]
I experience the same issue on Kafka 2.7.0 + Kafdrop 3.27.0. Downgrading Kafka below 3.25.0 in my case did not help.
Once I stop one of my broker in the Kafka cluster, Kafdrop becomes unavailable and eventually time out.
