### ISSUE TITLE
JSON support for consumer data

### ISSUE THREAD

**Issue by jim12321** [obsidiandynamics/kafdrop#18]
Hello.  So just want to say that we love this software.  Very useful.

We just wanted to have consumer data in JSON.

When you make a call to /topic/<topic name>

You get that in JSON, but it does not include the consumer group data table that you see in http:

<div id="consumers" class="col-md-4">
                        <h3>Consumers</h3>
                        <table id="consumers-table" class="table table-bordered table-sm small">
                            <thead>
                                <tr>
                                    <th>Group ID</th>
                                    <th>Combined Lag</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <a href="/consumer/***">****</a>
                                    </td>
                                    <td>155632</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

Could this data be added to the JSON request for topic/<topic name>?

Also could /consumer/<consumer name> endpoint support JSON too.  When sending Accept application/json it still sends HTML and not JSON.

Thanks

**Comment by ekoutanov** [comment]
Currently a bit tied up with work. There are a bunch of controllers that do this sort of thing already, so should mostly be a copy-paste job. Would you consider submitting a PR?

**Comment by jim12321** [comment]
Would love to help, but I am only a lowly Python programmer.  Not sure you want me to try and submit a PR.  ;)

**Comment by ekoutanov** [comment]
@jim12321 The modest coders are the best, in my experience ;)

**Comment by shaaimin** [comment]
add new api endpoint /topic/{topic-name}/consumers for get consumers for a topic
#49
