### ISSUE TITLE
Can we add feature to display LAG ?

### ISSUE THREAD

**Issue by kevin79059** [obsidiandynamics/kafdrop#182]
Hi, 
Can we add a feature to display LAG for each topic?

Example: how it will look for Kafka lag report. 

CURRENT-OFFSET | LOG-END-OFFSET | LAG
10175 | 10333 | 158

**Comment by ekoutanov** [comment]
We already have that in the consumer section

**Comment by kevin79059** [comment]
Sorry. i missed that part. i can see now. Thanks Emil. 
is there any plan to display lag report on home page or other ? It will be useful to view topics having lags.
