### ISSUE TITLE
Allow set pod annotations in helm chart

### ISSUE THREAD

**Issue by dkirrane** [obsidiandynamics/kafdrop#2]
For a cluster with Istio sidecar injection enabled I need to set the following pod annotations

```
      annotations:
        sidecar.istio.io/inject: "false"  
```

**Comment by ekoutanov** [comment]
@dkirrane I don't have Istio close at hand to do the necessary changes and testing. Would you mind submitting a pull request for the Helm charts that make the annotations configurable?
