### ISSUE TITLE
Need broker address when start kafdrop by jar?

### ISSUE THREAD

**Issue by gonggaohan** [obsidiandynamics/kafdrop#20]
I started kafdrop failed and it indicated that broker address cat't connect.

2019-08-25 21:52:51.946  INFO 421 [           main] o.a.k.c.c.AbstractConfig                 : AdminClientConfig values: 
        bootstrap.servers = [localhost:9092]
        client.dns.lookup = default
        client.id = 
        connections.max.idle.ms = 300000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        receive.buffer.bytes = 65536
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 120000
        retries = 5
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = https
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS

2019-08-25 21:52:51.965  INFO 421 [           main] o.a.k.c.u.AppInfoParser$AppInfo          : Kafka version: 2.2.1
2019-08-25 21:52:51.965  INFO 421 [           main] o.a.k.c.u.AppInfoParser$AppInfo          : Kafka commitId: 55783d3133a5a49a
2019-08-25 21:52:51.987  INFO 421 [           main] k.s.BuildInfo                            : Kafdrop version: 3.9.0-SNAPSHOT, build time: 2019-08-24T18:07:26.130Z
2019-08-25 21:52:51.994  WARN 421 [| adminclient-1] o.a.k.c.NetworkClient                    : [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2019-08-25 21:52:52.021  INFO 421 [ChildrenCache-1] k.s.CuratorKafkaMonitor                  : Topic confi

**Comment by ekoutanov** [comment]
Yes it's required, unless your brokers are on localhost:9092 (which is a default value). The property should be `kafka.brokerConnect`.

**Comment by gonggaohan** [comment]
But i am curious about why kafdrop need configured broker address before started, I think kafdrop can get all the broker information from zookeeper, and I set the zk address when start, below is command:
java --add-opens=java.base/sun.nio.ch=ALL-UNNAMED     -jar target/kafdrop-3.9.0-SNAPSHOT.jar --zookeeper.connect=100.91.212.111:2181

**Comment by ekoutanov** [comment]
In some cases it is possible — merely connecting to ZK should give your broker addresses.
In some other cases this model does not work. For example, if using SASL, broker addresses are not available. Also, most managed Kafka providers (AWS, Aiven, Instaclustr, etc.) block direct access to ZK, leaving you with having to specify bootstrap servers.

In the future, we may implement automatic defaulting of brokers from ZK. Alternatively, you're welcome to submit a PR :)

**Comment by gonggaohan** [comment]
ok, thanks so much:)

**Comment by ekoutanov** [comment]
I'll also update the README
