### ISSUE TITLE
Negative offset

### ISSUE THREAD

**Issue by NikolaLal** [obsidiandynamics/kafdrop#204]
Whenever I try to browse any topic I am getting: 

A 500 error has occurred: Request processing failed; nested exception is kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid negative offset
Stack trace
kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid negative offset at kafdrop.service.KafkaHighLevelAdminClient.listConsumerGroupOffsetsIfAuthorized(KafkaHighLevelAdminClient.java:91) at kafdrop.service.KafkaMonitorImpl.resolveOffsets(KafkaMonitorImpl.java:307) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1600) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) at kafdrop.service.KafkaMonitorImpl.getConsumerOffsets(KafkaMonitorImpl.java:316) at kafdrop.service.KafkaMonitorImpl.getConsumers(KafkaMonitorImpl.java:201) at kafdrop.controller.TopicController.topicDetails(TopicController.java:57) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:567) at

Anyone experienced this before?

It is working for other tools but not with Kafdrop.

Thanks in advance,
Nikola

**Comment by gireesh-kumar** [comment]
Same issue facing for me as well. Any solutions?

**Comment by giom-l** [comment]
Also getting this issue so I can't use kafdrop at the moment :-/

**Comment by aboutandre** [comment]
Please, if anyone found a solution for this post it here.
