### ISSUE TITLE
Trying connection to Secure Kafka (MSK) - giving TimeoutException

### ISSUE THREAD

**Issue by rldeep2889** [obsidiandynamics/kafdrop#206]
Hi,

I am trying to connect to Amazon MSK with SSL auth from EC2 instance. 

I am trying the command 

**docker run -d --rm -p 8080:9000 -e KAFKA_BROKERCONNECT='<host:port>' -e KAFKA_TRUSTSTORE='$(cat base-path/kafka.client.truststore.jks | base64)' -e KAFKA_KEYSTORE='$(cat base-path/kafka.client.keystore.jks | base64)'  -e KAFKA_KEYSTORE='$(cat base-path/kafka.client.keystore.jks | base64)' -e KAFKA_PROPERTIES='$(cat base-path/client.properties | base64)' obsidiandynamics/kafdrop:latest**

My **client.properties** file looks like the below 

ssl.security.protocol=SSL
ssl.endpoint.identification.algorithm=
ssl.truststore.password=****
ssl.truststore.type=JKS
ssl.keystore.password=****
ssl.keystore.type=JKS
ssl.key.password=****
ssl.truststore.location=<base-path>/kafka.client.truststore.jks
ssl.keystore.location=<base-path>/kafka.client.keystore.jks

But i am not able to connect as I am getting the below error 

> _errorAtts: {timestamp=Thu Oct 29 13:17:10 GMT 2020, status=500, error=Internal Server Error, message=Request processing failed; nested exception is kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment., trace=kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment._

PS : Other consumer apps are able to connect to MSK within the same vpc with the required details.

**Comment by MichaelDz6** [comment]
Have you tried adding `security.protocol=SSL`?

**Comment by alexvaque** [comment]
As I see in Kafka CLI
`[2021-12-27 17:33:17,922] WARN The configuration 'ssl.security.protocol' was supplied but isn't a known config. (org.apache.kafka.clients.producer.ProducerConfig)`

I think that you need
`security.protocol=SSL`
