### ISSUE TITLE
Usage in offline environments slow due to the use of google font in template

### ISSUE THREAD

**Issue by doggyde** [obsidiandynamics/kafdrop#21]
While most time it is a good and common idea to use fonts from google via links that point to google servers, it is quite slow if the server is not reachable from the docker container - connection timeout - will take 30 seconds for every page until time out is reached.

Maybe there is a way to include the font?

**Comment by ekoutanov** [comment]
Well spotted. I would imagine that embedding the font will make it faster overall, even in online environments.

I'm not an expert in font embedding. If you have a quick fix available at hand, would you mind raising a PR?

**Comment by doggyde** [comment]
I need to check with my scrum master if I can contribute during this sprint. If not I will contribute at a weekend on a private base. I've been reading through a german how-to in the context of the european privacy laws - shouldn't be too hard to archive.

**Comment by ekoutanov** [comment]
Does this issue somehow cross paths with GDPR?

**Comment by doggyde** [comment]
Since there most likely won't be visitors on kafdrop and in our case it is not even connected to the internet I guess no. But in general if you run a website and you use the link then you cannot guarantee that Google is not collecting visitors data and therefor you have to embed the fonts, so yes.

**Comment by ekoutanov** [comment]
Right, okay

**Comment by doggyde** [comment]
Got the okay from my managers - will do.

**Comment by doggyde** [comment]
Done - working well in our offline environment. Got no clue why the CI is not working ;)

**Comment by ekoutanov** [comment]
There's a problem with the current Travis CI setup; it doesn't work on PRs.

**Comment by ekoutanov** [comment]
Released in 3.8.1

**Comment by ekoutanov** [comment]
Thanks heaps for your help.
