### ISSUE TITLE
Use of a different port (other than 9000) on Docker version

### ISSUE THREAD

**Issue by bmkeafer2112** [obsidiandynamics/kafdrop#212]
I would like to use kafdrop access it through a different port other than the 9000 default. I am already using this port for another application that cannot be changed. Is there a way to change this default in the docker version?

**Comment by jonas-grgt** [comment]
Yes you can use the -p docker argument as in -p <port-on-host>:<port-inside-container>

`docker run -d --rm -p 9001:9000 ... obsidiandynamics/kafdrop` 

This will expose kafdrop at 9001 instead of 9000. 

Hope it helps!
