### ISSUE TITLE
No link available to view all messages page

### ISSUE THREAD

**Issue by fchishti** [obsidiandynamics/kafdrop#216]
There is no link/button available to view all message page when viewing the messages in message inspector. 

It will be nice to have a button in message inspector page to view all the messages in a given topic.

**Comment by ctrongduc** [comment]
@fchishti how would it work? in our setting, we have some topic with million messages, if I click the button would it pull everything on the topic and show on the page?

**Comment by fchishti** [comment]
@ctrongduc there is already functionality implemented where you can view all messages in a topic in the master branch. My issue was that there was no link in the UI to navigate to the particular page so I have added the button and created a pull request for it.
