### ISSUE TITLE
One issue with one partition ruin the whole thing

### ISSUE THREAD

**Issue by dxxvi** [obsidiandynamics/kafdrop#227]
I got this error message
```
Internal Server Error
A 500 error has occurred: Request processing failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition XXX-3 could be determined 
```
If errors like that can be ignored so that we can see other topics/partitions, then that will be great.

**Comment by ghost** [comment]
Same here!

**Comment by saurabh-bhoomkar** [comment]
@dxxvi I've faced the exact same issue with a specific partition which has basically brought the kafdrop down. But I'm more interested in knowing what that issue is with the topic partition; any helpful pointers on that ?
