### ISSUE TITLE
Is it possible to show messages as images?

### ISSUE THREAD

**Issue by ghost** [obsidiandynamics/kafdrop#229]
I'm sending and receiving images over Kafka. Can I view messages as images on Kafdrop?

**Comment by OneCricketeer** [comment]
If raw message data were shown, you'd have to have raw HTML in the topic. Note that rendering raw, unescaped HTML would be unsafe...

Plus, the messages [seem to be rendered as a  `<pre>` tag](https://github.com/obsidiandynamics/kafdrop/blob/master/src/main/resources/templates/topic-messages.ftlh#L48)
