### ISSUE TITLE
Port selection not working

### ISSUE THREAD

**Issue by senthil13** [obsidiandynamics/kafdrop#23]
Even though specfy different port than 9000, still the kafdrop listen on 9000.

```
ps ax | grep -i "kafdrop.jar" | egrep -v "grep" | awk '{print $1}'
1199

netstat -plant | grep 9000
tcp6       0      0 :::9000                 :::*                    LISTEN      1199/java

netstat -plant | grep 9010
tcp6       0      0 :::9010                 :::*                    LISTEN      1199/java
```

**Comment by shaaimin** [comment]
@senthil13 
which command did you used to start kafdrop?
like java -jar kafdrop-3.8.1.jar --server.port=9001 > kafdrop.log &

**Comment by senthil13** [comment]
Sorry for delay in response. 

below is the command i used. 

`nohup java -jar kafdrop.jar --zookeeper.connect=<servername:port> --server.port=9010 >> kafdrop.$(date +"%F").out &`

**Comment by shaaimin** [comment]
@senthil13 
i also tried on my local, it seems that port not be changed...

could you try the following one? i think it works.
nohup java -Dspring.application.json='{"server.port":9010}' -jar kafdrop.jar --zookeeper.connect=<servername:port> >> kafdrop.$(date +"%F").out &

**Comment by ekoutanov** [comment]
@senthil13 @shaaimin 

Kafdrop uses Undertow to serve both the user-facing content (web pages and REST APIs) as well as the `/actuator` endpoint for serving metrics. These can be served on two different ports, but both default to `9000`.

To change both, thereby freeing 9000 altogether, pass in the following arguments:
```
--server.port=9001 --management.server.port=9001
```

**Comment by ekoutanov** [comment]
Updated the README for the 'make-benefit of future generation' :) And closing issue.

**Comment by dlipofsky** [comment]
Environment variables `SERVER_PORT` and `MANAGEMENT_SERVER_PORT` also work, although the README only mentions the former.

**Comment by Bert-R** [comment]
Added it in #553
