### ISSUE TITLE
UI or API calls taking more than 15 minutes to load

### ISSUE THREAD

**Issue by alesanmed** [obsidiandynamics/kafdrop#233]
Hi all,

when I deploy locally Kafdrop and access the UI, it takes more than 3 minutes to load the UI. If I make a request to the kafdrop API takes more or less the same time. Since I've seen no one mentioning this, I'm starting to think that is something I did wrong.

Is there any troubleshooting guide or a DEBUG mode to see what could be causing this?

The kafdrop logs are not showing any errors. Here are the screenshots of the browser developer tools and postman:

![image](https://user-images.githubusercontent.com/9042789/106111906-ea39d700-614c-11eb-8864-d1216e9e1924.png)

![image](https://user-images.githubusercontent.com/9042789/106111960-f9b92000-614c-11eb-9e35-6838bc333ece.png)

The errors in the browser are:

![image](https://user-images.githubusercontent.com/9042789/106112013-0dfd1d00-614d-11eb-8674-ee7c4133a60d.png)

And the kafdrop logs just show:

```
errorAtts: {timestamp=Thu Jan 28 08:29:11 GMT 2021, status=404, error=Not Found, message=Not Found, path=/js/bootstrap.min.js.map}
```

**Comment by kevincoelho1989** [comment]
Same here, in my case takes 4 minutes to load, meanwhile this issue is not fixed, is there a version that doesn't behave like this?

**Comment by alesanmed** [comment]
I "fixed" it by increasing the resources. But that's not a real fix :(

**Comment by kevincoelho1989** [comment]
Tried to increase the heap size, but the perform hasn't change. How did you setup yours?

**Comment by alesanmed** [comment]
@kevincoelho1989 `JVM_OPTS="-Xms1024M -Xmx2048M"` 1Gb of minimum heap and 2 Gb of maximum heap size.

**Comment by senthil13** [comment]
I too has the same issue, Even I increased to heap but no improvement. one thing i noticed is kafdrop is fast when the total topic count is less than 500, if its more than ~ 650 + then its really slow.

**Comment by tolgabalci** [comment]
I have 736 topics and it takes a painful 1 minute, 7 seconds to load consistently.  Even if I refresh the page, it takes almost exactly the same amount of time.

I tried playing with JVM_OPTS settings, but did not seem to make any difference.

**Comment by jorkzijlstra** [comment]
I actually created a PR to tackle this issue: https://github.com/obsidiandynamics/kafdrop/pull/277 but its not moving forward yet
