### ISSUE TITLE
Helm Repository

### ISSUE THREAD

**Issue by syepes** [obsidiandynamics/kafdrop#236]
It would be great to be able to use your chart directly from the git repo.

Could you consider adding the [index.yaml](https://github.com/cloudworkz/kafka-minion-helm-chart/blob/master/index.yaml) so we could directly do:

`helm repo add kafdrop https://raw.githubusercontent.com/obsidiandynamics/kafdrop/master/chart`

As a reference you can have a look at: https://github.com/cloudworkz/kafka-minion-helm-chart

**Comment by ekoutanov** [comment]
That could work I suppose.

**Comment by syepes** [comment]
I am currently using the minion one and it works like a charm

**Comment by florianbachmann** [comment]
If I try this, I get a 404

```
➜  ~ helm repo add kafdrop https://raw.githubusercontent.com/obsidiandynamics/kafdrop/master/chart
Error: looks like "https://raw.githubusercontent.com/obsidiandynamics/kafdrop/master/chart" is not a valid chart repository or cannot be reached: failed to fetch https://raw.githubusercontent.com/obsidiandynamics/kafdrop/master/chart/index.yaml : 404 Not Found
➜  ~ 

```

can you please help
