### ISSUE TITLE
Docker container doesn't have a ENV to set the schema registry URL

### ISSUE THREAD

**Issue by wgarunap** [obsidiandynamics/kafdrop#24]
[docker registry description of available env variables ](https://hub.docker.com/r/obsidiandynamics/kafdrop)

2019-09-07 11:19:43.034 ERROR 6 [ XNIO-1 task-10] i.u.s.a.LoggingExceptionHandler          : UT005023: Exception handling request to /topic/trip/messages

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is io.confluent.common.config.ConfigException: Invalid value null for configuration schema.registry.url: Expected a comma separated list.

**Comment by ekoutanov** [comment]
You can probably add one pretty easily in the helm chart. I'm a bit hamstrung by time at the moment; would you mind submitting a PR?

**Comment by cg-nz** [comment]
Hi There

Great project, thanks very much for your time on this!

What is the environment var to use to specify the schema registry?
I did try a couple of iterations, but end up with the below error when viewing as avro deserialised.

`org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode`

Thanks!
cg

**Comment by ekoutanov** [comment]
@cg-nz I haven't personally played with Schema Registry in Kafdrop, but enable it, set the `SCHEMAREGISTRY_CONNECT` environment variable to the `host:port` of the schema registry.

**Comment by cg-nz** [comment]
@ekoutanov    thanks that seems to be ok. However appears that JsonNode package is missing, or has been moved. When changing to "AVRO" message view, the below error appears.

java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode

Shall I open a new issue?

Regards

**Comment by ekoutanov** [comment]
Yes please. Can you also include the full stack trace please as it's not obvious what in particular requires JsonNode.

**Comment by SpeedEX** [comment]
@ekoutanov I just had the same issue and got solved by adding SCHEMAREGISTRY_CONNECT environment variable. Shouldn't it better to document that SCHEMAREGISTRY_CONNECT environment variable also exists ?

**Comment by SpeedEX** [comment]
Hi all, shouldn't we mark this issue resolved as [this PR](https://github.com/obsidiandynamics/kafdrop/pull/83) got merged  ?
