### ISSUE TITLE
Delete Topic button results in Access Denied error

### ISSUE THREAD

**Issue by mkoziel2000** [obsidiandynamics/kafdrop#243]
When I click the "Delete topic" button for a given topic, it will initiate the deletion process with Kafka, however, it will also result in the Kafka broker crashing due to an "AccessDeniedException".  Getting the broker going again means manually removing the folder that it was complaining about trying to access.  Because the kafka broker crashed, the kafka connector that interfaces with the broker goes into a funky state as well and starts kicking out SSL handshake issues.  Its a big mess that requires rebooting a bunch of services to get going again.

Based on investigation on the net, it seems that deleting the topic requires stopping the lead broker associated with that topic first according to Kafka documentation.  Is this button functional for anyone? If so, whats the secret?  I don't want to operationalize this tool if I know that a mistaken button click can bring down services in the kafka cluster.

**Comment by edubriguenti** [comment]
Hi tried a simple scenario and it worked.
Maybe we need more information about your environment, like # of partitions, number of messages in this topic and so on.

My guess is that If the broker is taking too much time to delete a topic, the current implementation may raise an exception.

**Comment by mkoziel2000** [comment]
It turns out that this problem is a manifestation of a known problem with running Kafka where the data is stored on windows platforms.  When deleting topics, kafka throws AccessDenied errors because windows will not allow it to delete a file that still has open connections to it.  It seems Microsoft fixed it in their version of kafka, but confluent's version still has the bug.
