### ISSUE TITLE
My topic is on remote kafka broker and ssl protected , can i access my topic , and i have certs with me 

### ISSUE THREAD

**Issue by hotcoder** [obsidiandynamics/kafdrop#244]
My topic is on remote kafka broker and ssl protected , can i access my topic , and i have certs with me  ?

**Comment by lornajane** [comment]
I use something like this to access an SSL-protected Kafka broker with the docker version:

```
docker run -p 9000:9000 -e KAFKA_BROKERCONNECT=$SERVICEURI -e KAFKA_PROPERTIES="$(cat kafka.properties | base64)" -e KAFKA_TRUSTSTORE="$(cat client.truststore.jks | base64)" -e KAFKA_KEYSTORE="$(cat client.keystore.p12 | base64)" obsidiandynamics/kafdrop
```

There's more info on https://help.aiven.io/en/articles/3988677-using-kafdrop-web-ui-with-aiven-kafka (disclaimer, I work there) and this approach worked well for me.
