### ISSUE TITLE
Kafdrop too slow

### ISSUE THREAD

**Issue by senthil13** [obsidiandynamics/kafdrop#246]
Hi Team,

We are using the kafdrop for long time, so far no issues. But when we tried to use against a larger cluster say it has more than 3k topics then the kafdrop home page is too slow to load. We increased the heap/cpu and changed the java parameters too but still we have the slowness. Any suggestion will be appreciated. 

` $java_home --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Xms2g -Xmx2g -XX:+UseParallelOldGC -XX:MetaspaceSize=256m -jar $kafdrop_home/$process --zookeeper.connect=$zookeeper_list --kafka.brokerConnect=$kafka_list --schemaregistry.connect=$schema_list --server.port=9000 --topic.deleteEnabled=false --topic.createEnabled=false
`
Thanks
Senthil

**Comment by Wouter86** [comment]
While waiting for support, patching [this](https://github.com/Wouter86/kafdrop/commit/503257822137804623c9a14dee3d5008a7d492c2) in may unblock you. It has been proposed via PR but was unfortunately not accepted.

**Comment by jorkzijlstra** [comment]
I also created a PR to address this slowlyness: https://github.com/obsidiandynamics/kafdrop/pull/277 but its not moving forward yet
