### ISSUE TITLE
Timed out waiting for a node assignment. while connecting with TLS MSK 

### ISSUE THREAD

**Issue by Gouravjoshi05** [obsidiandynamics/kafdrop#249]
We are trying to connect secured MSK from kafdrop pod so getting below error.
Error:
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.

errorAtts: {timestamp=Thu Mar 18 11:20:33 GMT 2021, status=500, error=Internal Server Error, message=Request processing failed; nested exception is kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment., trace=kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.

**Content of kafka.properties file:**
ssl.security.protocol=SSL
ssl.protocol=SSL
ssl.truststore.type=JKS
ssl.keystore.password=xxxxx=
ssl.keystore.type=JKS
ssl.key.password=xxxxxx=
ssl.truststore.location=/kafka.truststore.jks
ssl.keystore.location=/kafka.keystore.jks

**Comment by randidwiputra** [comment]
you can try connect with kafka cli, testing with kafka cli, if use kafka cli has successed, so you can try konek MSK.
I using MSK too, I connect to MSK with OpenVPN.

**Comment by Gouravjoshi05** [comment]
my other applications are able to connect MSK.
i am not sure that my property file is correct or not.

**Comment by jgrammen-agilitypr** [comment]
I was able to connect to MSK by only specifying the first configuration item in my kafka.properties file
`security.protocol=SSL`

**Comment by shlomi-viz** [comment]
I added the following when running the service with docker
```-e KAFKA_PROPERTIES="$(cat kafka.properties | base64)" ```

and in my `kafka.properties` I have:
```
security.protocol=SSL
ssl.security.protocol=SSL
```

**Comment by alexvaque** [comment]
be carefully because using the Kafka CLI  with:

`ssl.security.protocol=SSL
`
I see that is not necessary that key-value in the properties


` ./kafka-console-producer.sh --broker-list XXXXXXX.amazonaws.com:9096  --producer.config client.properties --topic TEST
`

`[2021-12-27 17:33:17,922] WARN The configuration 'ssl.security.protocol' was supplied but isn't a known config. (org.apache.kafka.clients.producer.ProducerConfig)
`
