### ISSUE TITLE
[Question] How to connect from Python KSQL and cannot see partition/replication > 1?

### ISSUE THREAD

**Issue by scheung38** [obsidiandynamics/kafdrop#250]
Can ping: 

ping kafdrop-example.cloud.okteto.net 
PING kafdrop-example.cloud.okteto.net (35.225.69.73): 56 data bytes
64 bytes from 35.225.69.73: icmp_seq=0 ttl=102 time=105.680 ms
64 bytes from 35.225.69.73: icmp_seq=1 ttl=102 time=102.649 ms

Can call from Postman/Insomnia without any Header metadata or configs:

```
kafdrop-scheung38.cloud.okteto.net  or
https://kafdrop-example.cloud.okteto.net/v2/api-docs

{
  "swagger": "2.0",
  "info": {
    "description": "JSON APIs for Kafdrop",
    "title": "Kafdrop API"
  },
  "host": "kafdrop-example.cloud.okteto.net",
  "basePath": "/",
  "tags": [
    {
    }
}
```
    

Not sure why in Python:

```
from ksql import KSQLAPI

Tried all 3 combo:
client = KSQLAPI("kafdrop-example.cloud.okteto.net/")
client = KSQLAPI("http://kafdrop-example.cloud.okteto.net/")
client = KSQLAPI("https://kafdrop-example.cloud.okteto.net/")
print(client)
```

A 404 error has occurred : Not Found

**Comment by OneCricketeer** [comment]
Kafdrop isn't a KSQL REST server
