### ISSUE TITLE
[Question] How to consumer messages?

### ISSUE THREAD

**Issue by scheung38** [obsidiandynamics/kafdrop#257]
after sending a message:
curl -X POST https://producer-kafka-sample.cloud.okteto.net -H “Content-Type: application/json” -d ‘{“message”:“foo”}’
how to read from topic from curl, (not from consumer/app.py)
consumer> curl -X GET https://kafdrop-kafka-sample.cloud.okteto.net
returns the complete HTML instead of JSON? (edited)

**Comment by OneCricketeer** [comment]
Did you look at the source code? 

Seems like `GET /topics/:name/allmessages`

https://github.com/obsidiandynamics/kafdrop/blob/master/src/main/java/kafdrop/controller/MessageController.java#L88
