### ISSUE TITLE
[Question] How to consumer messages?

### ISSUE THREAD

**Issue by scheung38** [obsidiandynamics/kafdrop#258]
after sending a message:
curl -X POST https://producer-kafka-sample.cloud.okteto.net -H “Content-Type: application/json” -d ‘{“message”:“foo”}’

how to read from topic from curl, (not from consumer/app.py)

consumer> curl -X GET https://kafdrop-kafka-sample.cloud.okteto.net
returns the complete HTML instead of JSON? 

![Screenshot 2021-03-28 at 03 18 38](https://user-images.githubusercontent.com/1273014/112740363-4fa31c00-8f74-11eb-9046-9bfe18702b09.png)

Tried:

https://kafdrop-kafka-sample.cloud.okteto.net/topic

https://kafdrop-kafka-sample.cloud.okteto.net/v2/api-docs

**Comment by OneCricketeer** [comment]
Duplicates #257
