### ISSUE TITLE
Bintray going away may 1st 2021

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [obsidiandynamics/kafdrop#260]
Bintray service is being shutdown may 1st 2021
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Kafdrop uses bintray to distribute the .deb binaries, kafdrop will need to migrate to new method of provided deb compatible repo's.

**Comment by jgrammen-agilitypr** [comment]
This is now critical as the sunset will happen in 3 days

**Comment by jgrammen-agilitypr** [comment]
You can now no longer download kafdrop as bintray is offline

**Comment by jgrammen-agilitypr** [comment]
emailed user "ekoutanov" who appears to be the primary contact for the repo, no response as of yet.
This currently no way to download pre compiled versions of this repository.

**Comment by Alfusainey** [comment]
In  the meantime,  the alternatives for running kafdrop locally are (1) [using docker](https://github.com/obsidiandynamics/kafdrop#running-with-docker) or (2) clone & build the source with maven (see [building section](https://github.com/obsidiandynamics/kafdrop#building) of the readme)

**Comment by smshr** [comment]
The build using command `mvn clean package` fails with error: 
```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1224)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
```
I am using OpenJDK16.

**Comment by combrs** [comment]
Hello, no solution for now? Wants to download jar release also, and can't
Looks like abandoned project, only source code accessible
No pull requests was accepted in current year

**Comment by pas8sion** [comment]
> The build using command `mvn clean package` fails with error:
> 
> ```
> Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
>     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1224)
>     at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
> ```
> 
> I am using OpenJDK16.

I have built it with mvn and openjdk version "11.0.1" 2018-10-16 just fine to kafdrop-3.27.0.jar

**Comment by mjalil** [comment]
> > The build using command `mvn clean package` fails with error:
> > ```
> > Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
> >     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1224)
> >     at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
> >     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
> >     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
> >     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am using OpenJDK16.
> 
> I have built it with mvn and openjdk version "11.0.1" 2018-10-16 just fine to kafdrop-3.27.0.jar

please put it somewhere for us to be able to download. I'm not going to build it myself

**Comment by davideicardi** [comment]
We are trying to "resurrect" ;-) the project. See #323

**Comment by eriksencosta** [comment]
> > > The build using command `mvn clean package` fails with error:
> > > ```
> > > Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
> > >     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1224)
> > >     at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
> > >     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
> > >     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
> > >     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I am using OpenJDK16.
> > 
> > 
> > I have built it with mvn and openjdk version "11.0.1" 2018-10-16 just fine to kafdrop-3.27.0.jar
> 
> please put it somewhere for us to be able to download. I'm not going to build it myself

@mjalil on 3.27.0, you can just edit the `pom.xml` file and update the Lombok version (which supports OpenJDK 17 in its 1.18.22 [release](https://projectlombok.org/changelog)). The master version does not lock this dependency anymore but I haven't tested it.

Change the version from:

```xml
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.8</version>
        </dependency>
```

To:

```xml
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
        </dependency>
```

Then build it again:

    $ mvn clean package

And then start Kafdrop:

    $ java -jar ./target/kafdrop-3.27.0.jar --kafka.brokerConnect=<broker-address-and-port>

**Comment by davideicardi** [comment]
From now on, we have switched the project to use Github actions and Github releases. So you can find the new jar artifact inside: https://github.com/obsidiandynamics/kafdrop/releases/tag/3.28.0

**Comment by ekoutanov** [comment]
We can probably remove any mention of bintray in `pom.xml`.
