### ISSUE TITLE
Unable to use different port due to hardcoded management server port

### ISSUE THREAD

**Issue by yogsoft** [obsidiandynamics/kafdrop#267]
Due to hardcoded port for management server, one cannot specify different port to run Kafdrop.

src/main/resources/application.yml

Workaround is to specify management server port via JAVA_OPTS

**Comment by OneCricketeer** [comment]
Any Spring property can be overridden with command options

`java jar kafdrop.jar --spring.management.port=xx`

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.command-line-args
