### ISSUE TITLE
better docs on event hub connection

### ISSUE THREAD

**Issue by wccropper** [obsidiandynamics/kafdrop#268]
I'm finding it difficult to understand how to connect this to our Event Hub via a Kubernetes Helm deployment. For both Python and Go you need the following:
EVENTHUB_CONNECTION_STRING
EVENTHUB_ENDPOINT

I understand that the ENDPOINT maps to the brokerConnect. I don't know how to pass the CONNECTION_STRING and how to do so securely.

**Comment by OneCricketeer** [comment]
Related #294
