### ISSUE TITLE
Polling Issues - Kafdrop consumer is not picking requested count

### ISSUE THREAD

**Issue by AmareeshTejVattikuti** [obsidiandynamics/kafdrop#271]
Hi All,

Last few days I was working with Kafdrop and found few issues with the consuming part.

1) Consider a topic is having around 10k messages and I'm trying to fetch around 200 messages with 'offset' as '0' and messages as '200'. 
   So when ever Offset is set to '0', irrespective of the count we requested, kafdrop is pulling only one message which is having 
   offset '0'.

![image](https://user-images.githubusercontent.com/82869075/115764719-87f71800-a3c3-11eb-928d-b8c88756753f.png)

2) I tried increasing the message fetch limit form default 100 to 10000 just to see how it works.
But the strange thing is, Consumer poll is not picking requested count.
For example: I requested 1500 messages out of 10000, consumer has just picked 945 messages. Not sure whether any config i need to change for this to pick all the messages.

Can someone please help me out on this issue?

**Comment by yashgoyal60** [comment]
If this is an open issue. Can I take this one?
