### ISSUE TITLE
Kafdrop UI has issue using IAM access control to address encryption,authentication and authorisation

### ISSUE THREAD

**Issue by manee2k6** [obsidiandynamics/kafdrop#283]
Hi,
  I have a MSK cluster in AWS, it has the IAM access control enabled as authentication.

I dont see kafdropui support by default, as i see we need to add a dependency and additional properties to KafdropUI.

I have cloned this project and added the configuration to enable this feature in kafdrop. I see some challenges.

**client.properties**
ssl.truststore.location=<PATH_TO_TRUST_STORE_FILE>
security.protocol=SASL_SSL
sasl.mechanism=AWS_MSK_IAM
sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

**dependency**
<dependency>
    <groupId>software.amazon.msk</groupId>
    <artifactId>aws-msk-iam-auth</artifactId>
    <version>1.0.0</version>
</dependency>

reference link: https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

Your support would be highly appreciated.

Thanks
Manivannan.C

**Comment by mbartusiak** [comment]
What error message do you get? After adding the aws-msk-iam-auth as a dependency for kafdrop I ran it without any issues.

**Comment by creed123** [comment]
We have been able to run kafkadrop within a pod in eks and its able to connect to msk using the iam role scoped to the pods service account. 
https://github.com/obsidiandynamics/kafdrop/pull/287

**Comment by fabioformosa** [comment]
> What error message do you get? After adding the aws-msk-iam-auth as a dependency for kafdrop I ran it without any issues.

I've reported the errors I get here:
https://github.com/obsidiandynamics/kafdrop/pull/275#issuecomment-862420719
