### ISSUE TITLE
Can not access Kafka server from outside

### ISSUE THREAD

**Issue by sstevenphan** [obsidiandynamics/kafdrop#289]
Hi, my name is Steven. I'm facing problem after installing Kafdrop in azure VM  by docker-compose cli. I can not push message to Kakfa server at port 9092 or consume topic message as well. I think I'm missing some configuration for outside accessing. Please help me

**Comment by OneCricketeer** [comment]
Read this https://www.confluent.io/blog/kafka-listeners-explained/
