### ISSUE TITLE
Can't download jar file

### ISSUE THREAD

**Issue by mdev1987** [obsidiandynamics/kafdrop#290]
Hi 
I can't download the jar file.
The link [Bintray](https://bintray.com/obsidiandynamics/kafdrop/download_file?file_path=com%2Fobsidiandynamics%2Fkafdrop%2Fkafdrop%2F3.27.0%2Fkafdrop-3.27.0.jar) redirect to [Jfrog](https://jfrog.com/center-sunset/?file_path=com%2Fobsidiandynamics%2Fkafdrop%2Fkafdrop%2F3.27.0%2Fkafdrop-3.27.0.jar).

**Comment by jgrammen-agilitypr** [comment]
See related issue #260
