### ISSUE TITLE
Configure docker image to use events hub

### ISSUE THREAD

**Issue by persiandeveloper** [obsidiandynamics/kafdrop#294]
Hi

I can not find the configuration or a guide for the docker image on "How to configure Kafdrop to use Azure Event Hubs".

I Use the following but it does not work : 

```
environment: 
      KAFKA_BROKERCONNECT: [namespace].servicebus.windows.net:9093
      KAFKA_security_protocol: SASL_SSL
      KAFKA_sasl_mechanism: PLAIN
      KAFKA_sasl_jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb:// [namespace]servicebus.windows.net/;SharedAccessKeyName==";
```

**Comment by jeff-lauterbach-by** [comment]
I was successful in getting this working

Either use `KAFKA_PROPERTIES` env variable and provide a base64 encoded value of a properties file with the following propeties
```properties
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb:// [namespace]servicebus.windows.net/;SharedAccessKeyName==";
```

Or put these properties into a file named `kafka.properties` and mount it into the root of the container
```
  volumes:
    -  ./kafka.properties:/kafka.properties
```

**Comment by persiandeveloper** [comment]
> I was successful in getting this working
> 
> Either use `KAFKA_PROPERTIES` env variable and provide a base64 encoded value of a properties file with the following propeties
> 
> ```ini
> security.protocol=SASL_SSL
> sasl.mechanism=PLAIN
> sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb:// [namespace]servicebus.windows.net/;SharedAccessKeyName==";
> ```
> 
> Or put these properties into a file named `kafka.properties` and mount it into the root of the container
> 
> ```
>   volumes:
>     -  ./kafka.properties:/kafka.properties
> ```

It worked.
