### ISSUE TITLE
Dropdown for Protobuf Message name

### ISSUE THREAD

**Issue by QuinnBast** [obsidiandynamics/kafdrop#295]
Once a protobuf schema has been loaded into kafkdrop for parsing, kafdrop requires you to manually type in the Protobuf message name to deserialize the messages on the topic. Since the schemas have already been provided it would be nice to have a dropdown list here that is pre-populated with a list of all of the possible Protobuf messages to deserialize instead of manually having to type in the protobuf message name every time.

![Screenshot from 2021-08-04 13-16-17](https://user-images.githubusercontent.com/22599103/128241500-f393f1af-ebd9-414f-94c4-84aaf0043a83.png)

**Comment by tanner0101** [comment]
+1. Would also be nice if the descriptor menu could keep the previously selected descriptor after clicking "view messages".

**Comment by QuinnBast** [comment]
Bump

**Comment by QuinnBast** [comment]
Reopen

**Comment by Bert-R** [comment]
@QuinnBast We currently do not have time to implement this feature, but we welcome a pull request to add it.
