### ISSUE TITLE
Deleting topic redirects to http, even if kafdrop runs behind https reverse proxy

### ISSUE THREAD

**Issue by fnordian** [obsidiandynamics/kafdrop#297]
When I delete a topic, my browser gets redirected to kafdrop's domain-name, but uses http instead of https.

**Comment by jamesorlakin** [comment]
To those coming from Google, I found adding `--server.forward-headers-strategy=NATIVE` to the environment variable `CMD_ARGS` fixed this. Of course the reverse proxy will be needing to set appropriate headers (X-Forwarded-Proto, etc) for this to work.

**Comment by OmprakashPaliwal** [comment]
> To those coming from Google, I found adding `--server.forward-headers-strategy=NATIVE` to the environment variable `CMD_ARGS` fixed this. Of course the reverse proxy will be needing to set appropriate headers (X-Forwarded-Proto, etc) for this to work.

I tried this but it doesn't fix the issue. I am using 3.27 version of kafka-drop
