### ISSUE TITLE
What is the future plan to add basic authentication and multicluster support

### ISSUE THREAD

**Issue by ankurjains** [obsidiandynamics/kafdrop#305]
Hi Team,

I am looking if there is any active plan to add basic auth like cmak and multicluster support in kafdrop ? please suggest or shed some light @ekoutanov

**Comment by adarsh1297** [comment]
> Hi Team,
> 
> I am looking if there is any active plan to add basic auth like cmak and multicluster support in kafdrop ? please suggest or shed some light @ekoutanov

You can add use SecurityFilterChain for creating bean and can store password in application.properties file
