### ISSUE TITLE
Fork Kafdrop due to inactivity?

### ISSUE THREAD

**Issue by davideicardi** [obsidiandynamics/kafdrop#321]
Hello everybody!

Current maintainer of Kafdrop is not more active on the project. (@ekoutanov please correct me if I'm wrong :-) )

So I'm thinking to create a fork inside a new [kafdrop organization](https://github.com/kafdrop).
But I need some help. Is someone interested in joining the organization?

If I found at least 2/3 developers I think we can try to continue the work in our spare time.

**Comment by aragozin** [comment]
@davideicardi please count me in

**Comment by mcs** [comment]
Yeah, why not? It's too useful to let it die a maintenance death...

**Comment by rachitnovostack** [comment]
Yes, That'll be really great!

And please review PR #282 to your fork

**Comment by fstaudt** [comment]
@davideicardi 

You can count me in

**Comment by davideicardi** [comment]
I have been contacted by @ekoutanov, and fortunately he says that kafdrop is still active!! So no need to fork, that is always a good thing.🥳

But we still need your help, so please stay tuned for further news!

I will close the Kafdrop organization.

**Comment by ekoutanov** [comment]
Heya folks,

Firstly, thanks everyone who's put their hand up for contributing to the project, and all those who're thinking of doing so. Unfortunately, I haven't been able to commit any time over the last year to do any work on it.

@davideicardi and I have indeed had a few email exchanges to determine what the best way forward is. The consensus for now is to maintain the present GitHub repo, which is heavily SEO-optimised, and to add people as maintainers.

All the best!
