### ISSUE TITLE
Custom Config not showing on topics.

### ISSUE THREAD

**Issue by moranpatrick** [obsidiandynamics/kafdrop#34]
Hi,

When creating topics I am setting config values (segment.bytes, cleanup.policy etc) but these values do not appear in the configuration section for the topic and the custom config column is set to "no". They would have previously shown when using the Home Advisor Kafdrop. Has something changed here?

Thanks

**Comment by ekoutanov** [comment]
Thanks for reporting. 

> Has something changed here?

Oh yes, the code base had to be almost entirely rewritten. I wouldn't be surprised if something slipped through the cracks.

I'll take a look.

**Comment by ekoutanov** [comment]
Fix committed. About to cut a release.

**Comment by ekoutanov** [comment]
Released in 3.11.2

**Comment by moranpatrick** [comment]
Topic configuration displaying correctly in 3.11.2
Thanks @ekoutanov
