### ISSUE TITLE
Kafdrop docker-compose fails

### ISSUE THREAD

**Issue by roland-becsi-veratrak** [obsidiandynamics/kafdrop#342]
Steps to reproduce:

1. Clone this repo
2. Cd cd docker-compose/kafka-kafdrop/
3. docker compose up

kafdrop_1  | 2022-01-31 13:01:53.647 ERROR 1 [           main] o.s.b.SpringApplication                  : Application run failed
kafdrop_1  | 
kafdrop_1  | org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/kafka/annotation/KafkaListenerConfigurationSelector.class] cannot be opened because it does not exist

Please let me know what else I should post here to further debug the issue.
Thanks

**Comment by davideicardi** [comment]
You are working on the latest version?

**Comment by roland-becsi-veratrak** [comment]
> You are working on the latest version?

Hi, yes I have used the unedited docker compose file from this repo. I assumed the image points to the latest docker image, changing the tag to `image: obsidiandynamics/kafdrop:latest` does not solve the issue.
I'm using
docker desktop 3.6.0 (67351)
compose 1.29.2
Mac mini (M1, 2020)

Thanks

**Comment by davideicardi** [comment]
Sorry, but I'm unable to reproduce this problem. To ensure you are running on latest version specify image with `obsidiandynamics/kafdrop:3.28.0`

**Comment by OneCricketeer** [comment]
> Mac mini (M1, 2020)

You can see on the `OS/arch` labels that the M1 ARM platform is not supported. 

- https://hub.docker.com/r/obsidiandynamics/kafdrop/tags
- https://hub.docker.com/r/obsidiandynamics/kafka/tags

Related #302

**Comment by altaiezior** [comment]
> > Mac mini (M1, 2020)
> 
> You can see on the `OS/arch` labels that the M1 ARM platform is not supported.
> 
> * https://hub.docker.com/r/obsidiandynamics/kafdrop/tags
> * https://hub.docker.com/r/obsidiandynamics/kafka/tags
> 
> Related #302

I have added a fork which supports M1 image, if you want to give it a spin.

Note: Only for development purpose.

**Comment by erdem** [comment]
+1
