### ISSUE TITLE
Kafdrop connection to an Kafka server with just SSL (not SASL) does not work

### ISSUE THREAD

**Issue by Bert-R** [obsidiandynamics/kafdrop#343]
This ticket actually duplicates #201, which was closed because it's stale. However, the issue is still relevant to us and a fix is available in #202. Can you please look into that PR and merge it in? That way, we can use the standard Kafdrop image instead of having to maintain our own one.

**Comment by davideicardi** [comment]
Ok, I will reopen the original ticket.
