### ISSUE TITLE
Release 3.29.0

### ISSUE THREAD

**Issue by jorkzijlstra** [obsidiandynamics/kafdrop#349]
I created a PR to get the current master released on dockerHub. https://github.com/obsidiandynamics/kafdrop/pull/348

What is the normal process of releasing this repo?

**Comment by Bert-R** [comment]
Code-wise, it's slightly different than you did. Releasing means removing the ``-SNAPSHOT`` suffix from the version number. Incrementing the version number is done as next change after the release, while re-adding the ``-SNAPSHOT`` suffix.

**Comment by jorkzijlstra** [comment]
Ah thanks. I should have noticed that while looking at the tags on docker.

The new PR is: https://github.com/obsidiandynamics/kafdrop/pull/350

**Comment by jorkzijlstra** [comment]
Thnx for releasing it.
