### ISSUE TITLE
Publish to artifacthub?

### ISSUE THREAD

**Issue by brsolomon-deloitte** [obsidiandynamics/kafdrop#357]
Hi, it'd be great to have this chart officially available on https://artifacthub.io/.

Currently there is https://artifacthub.io/packages/helm/main/kafdrop which is unofficial and points to a very outdated version.

You can use [GitHub pages for the repository](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417) with minimal setup.

**Comment by davideicardi** [comment]
If someone is able to create a PR I think we can publish it during CI pipeline

**Comment by florianbachmann** [comment]
this would be awesome :-)
