### ISSUE TITLE
Multi cluster support

### ISSUE THREAD

**Issue by bhataprameya** [obsidiandynamics/kafdrop#360]
In any company, there will be multiple Kafka clusters. having a different instance for each with a different URL is not a feasible solution. So if kafdrop can support multiple cluster that will be greats

**Comment by davideicardi** [comment]
Hi @bhataprameya . I understand your point, but I think that this will add a lot of complexity inside kafdrop.

Maybe you can configure all kafdrop instances like `cluster1.kafdrop.company.org`, `cluster2.kafdrop.company.org`, ... but each domain will point to a different kafdrop instance. In my opinion is the more flexible and powerful solution.

**Comment by OneCricketeer** [comment]
Depending on how easily you can deploy the instance(s), you could use a reverse proxy (e.g. single or HA Nginx deployment) to redirect `/cluster1...N` individual kafkadrop instances

**Comment by sathyarajagopal** [comment]
In my opinion it may not be a best practice to do cross cluster connections. Cluster setup is mainly to handle HA and failovers. The correct solution is to standup separate instances in separate clusters based on your needs.
