### ISSUE TITLE
Failed to instantiate [org.apache.curator.framework.CuratorFramework]: Factory method 'serviceDiscoveryCuratorFramework' threw exception; nested exception is java.lang.NullPointerException: connectionString cannot be null

### ISSUE THREAD

**Issue by jmgomez77** [obsidiandynamics/kafdrop#361]
[error-stack.txt](https://github.com/obsidiandynamics/kafdrop/files/8306380/error-stack.txt)

Fixed by adding -Dzookeeper.connect to startup script.

java -Dzookeeper.connect=10.12.27.100:2181 -jar target/kafdrop-2.1.0.jar \
    --kafka.brokerConnect=10.12.27.100:9092 --add-opens=java.base/sun.nio.ch=ALL-UNNAMED

**Comment by jmgomez77** [comment]
I see it's in README.md but it's not in the GETTING STARTED section:

java --add-opens=java.base/sun.nio.ch=ALL-UNNAMED \
    -jar target/kafdrop-<version>.jar \
    --kafka.brokerConnect=<host:port,host:port>,...

**Comment by davideicardi** [comment]
I think it is related to this note:

> Note: As of Kafdrop 3.10.0, a ZooKeeper connection is no longer required. All necessary cluster information is retrieved via the Kafka admin API.
