### ISSUE TITLE
error adding in multiple brokers using helm

### ISSUE THREAD

**Issue by nightHawk13998** [obsidiandynamics/kafdrop#363]
When creating a values.yaml I enter all the Kafka Brokers as suggested by the helm chart.
--set kafka.brokerConnect=<host:port,host:port>
IE translates to --set kafka.brokerConnect=kafka1:9092,kafka2:9092

When running the helm install I get an error stating Error: failed parsing --set data: key "kafka2:6667" has no value (cannot end with ,)

What is the correct way to add in multiple brokers? 
If I only enter 1 broker it works and I can then edit the yaml to include all brokers and it works correctly.

**Comment by OneCricketeer** [comment]
Try putting quotes around the value so your shell treats the whole string as one literal
