### ISSUE TITLE
 The broker does not support LIST_OFFSETS with version in range [2,7]. The supported range is [0,1].

### ISSUE THREAD

**Issue by Hurria** [obsidiandynamics/kafdrop#364]
When I click the topic link, there's an error: 
Internal Server Error
A 500 error has occurred: Request processing failed; nested exception is org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support LIST_OFFSETS with version in range [2,7]. The supported range is [0,1].

**Comment by OneCricketeer** [comment]
What version of Kafka are you running?

**Comment by Hurria** [comment]
> What version of Kafka are you running?

My Kafka version is 2.1.0

**Comment by ArranOakes** [comment]
I also am seeing the same error, any help would be appreciated, thanks

**Comment by starryrbs** [comment]
I also am seeing the same error, any help would be appreciated, thanks
