### ISSUE TITLE
Using Kafdrop with SASL_SSL to connect to secure Kafka brokers

### ISSUE THREAD

**Issue by ChrisDavis3587** [obsidiandynamics/kafdrop#368]
I have a three broker kafka cluster that is secured using SASL_SSL with SSL interbroker communication.  From everything I can determine the brokers are up and running and communicating correctly.  When I try to run Kafdrop 3.29.0 (as a jar) from the command line, on one of the brokers, Kafdrop refuses to connect and fails.  For testing, I have shutdown kafka on broker2 and broker 3 and now I am attempting to launch Kafdrop on broker2 and have it attempt to connect to kafka running on broker1 using the following command line.

java --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -jar /home/user/kafdrop-3.29.0.jar --kafka.brokerConnect=sdl-secure-kafka-01:9093 --server.port=80 --management.server.port=80 --kafka.properties=/home/user/kafdrop.properties

with the following kafdrop.properties file:

security.protocol=SSL
sasl.mechanism=PLAIN
ssl.protocol=TLS
ssl.endpoint.identification.algorithm=
ssl.truststore.location=/home/clusteruser/kafka.server.truststore.jks
ssl.truststore.password=User6479
ssl.truststore.type=JKS
ssl.keystore.location=/home/clusteruser/kafka.server.keystore.jks
ssl.keystore.password=User6479
ssl.keystore.type=JKS
ssl.key.password=User6479
enable.ssl.certificate.verification=false
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
   username=\"kafka\" \
   password=\"kafka-secret\";

There isn't much returned by kafdrop when this situation fails, but when running kafka from the console on broker1, I get a SSL handshake error from ZK_BROKER, which indicates that Kafdrop is reading or handling my SSL certificates correctly.

If more information is needed to debug this issue, please respond so that I can provide it.

**Comment by mysberantoson** [comment]
Hello,
 I have the same problem when I run Kafdrop 3.29.0 (as a jar) from the command line.
I have 2 brokers and kafdrop refuse to connect to them.
I have the same properties file as you.

Do you get the solution please ?

Sincerely,

**Comment by zwessels** [comment]
in case it help anybody else, it worked for me when i renamed the properties file to `kafka.properties`

e.g.

```
java --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -jar \
/home/user/kafdrop-3.29.0.jar \
--kafka.brokerConnect=sdl-secure-kafka-01:9093 \
--kafka.properties=kafka.properties
```
