### ISSUE TITLE
Create Topic & manage ACLs via kafdrop

### ISSUE THREAD

**Issue by MrMoronIV** [obsidiandynamics/kafdrop#37]
I'm probably asking the obvious here, but are there are any plans to support creating topics and manage ACL rules or even zookeeper users (SCRAM)?

It seems to be the last missing piece in managing a kafka cluster :)

**Comment by ekoutanov** [comment]
Yes it would be nice. However, I'm a little short on time at the moment. Always looking for new contributors :)

**Comment by ekoutanov** [comment]
Both are now done.

**Comment by harshamehra** [comment]
> Both are now done.

I have a question, does this project currently has the ability to add ACL's ?

**Comment by ekoutanov** [comment]
No, but it would be an awesome feature to have. Wanna give it a crack?

**Comment by harshamehra** [comment]
Sure , I did add ACL's fairly new to Kafka but I feel we need to implement the feature for adding Users as well ? I can probably work on it and raise a PR sounds good ?

**Comment by ekoutanov** [comment]
Sounds good indeed. Essentially we need a form to be able to add literal and prefix-bases ACLs to arbitrary entities.
