### ISSUE TITLE
Variabilize Configuration File

### ISSUE THREAD

**Issue by ADefossez-Zenika** [obsidiandynamics/kafdrop#38]
Hi all, 

I need, in order to run Kafkdrop in my context, to override those properties-file location.

https://github.com/obsidiandynamics/kafdrop/blob/391b0102893ddc2829fed2558f28c4093b202082/src/main/java/kafdrop/config/KafkaConfiguration.java#L19

I can provide a PR, if you want to.

Is it OK for you ?

**Comment by ekoutanov** [comment]
Yes please.

**Comment by ekoutanov** [comment]
Reviewed and left some comments. Thanks @ADefossez-Zenika .
