### ISSUE TITLE
Don't force ENV variables to add configuration

### ISSUE THREAD

**Issue by PierreR** [obsidiandynamics/kafdrop#384]
The current setup seems to force the user to use ENV variables to configure anything.
For instance, the KAFKA_PROPERTIES_FILE file is removed if we don't specify an ENV called KAFKA_PROPERTIES:
https://github.com/obsidiandynamics/kafdrop/blob/master/src/main/docker/kafdrop.sh#L42-L43

I am not sure to understand why we cannot mount such properties file through a secret/configmap directly.

**Motivation**
If we want to use an external Vault such as Hashicorp Vault to hide sensitive information, it is more complex to do so with ENV variables as we would need to hack the container args with:
```
args:
            ['sh', '-c', 'source /vault/secrets/config && <entrypoint script>']
```
Thanks for your help

**Comment by PierreR** [comment]
Now I am wondering if I should go on using Kafdrop. Is this project still alive ?

**Comment by davideicardi** [comment]
Project is still alive, but any help is appreciated.
I'm trying to triage issues and PRs but I rarely do any actual code.
