### ISSUE TITLE
Basic auth for your schema registry connection does not work

### ISSUE THREAD

**Issue by EhsanMo** [obsidiandynamics/kafdrop#398]
Hi all, 
By setting the schemaregistry for basic authentication, UI does not ask users to enter user/pass. 
Is there any further setting needed?
sample config: 
`SCHEMAREGISTRY_AUTH: test:test`
Our environment is Kubernetease and the kafdrop version is 3.27.0

**Comment by primexpy** [comment]
docker run --name kafdrop -d -p xxx:xxx \
    -u root --privileged=true \
    -e KAFKA_BROKERCONNECT=xxxxxx:9092 \
    -e SERVER_SERVLET_CONTEXTPATH="/" \
    -e SCHEMAREGISTRY_AUTH="test=test" \
    --restart=always \
    obsidiandynamics/kafdrop:3.30.0

By setting the schemaregistry for basic authentication, UI does not ask users to enter user/pass。
