### ISSUE TITLE
Allow setting the root context path

### ISSUE THREAD

**Issue by dkirrane** [obsidiandynamics/kafdrop#4]
If I set the ingress path to `/kafkdrop` the UI doesn't load.

```
ingress:
  enabled: true
  path: /kafdrop
```

I believe this is because we'd also need to set the servlet context path for the Spring Boot app to 

```
server.servlet.context-path=/kafdrop
```

**Comment by ekoutanov** [comment]
Hi @dkirrane, thanks for calling that out. We should look into making the servlet context path configurable. Unfortunately it's not a simple as setting `server.servlet.context-path`, as the original Kafdrop (2.x) app was written using absolute URLs :( Will have to go over each FreeMarker file to relative-_ise_ it.

**Comment by ekoutanov** [comment]
That's now done (release 3.6.0) and in dockerhub. Can you please check it out.
