### ISSUE TITLE
CVEs in the 3.30.0

### ISSUE THREAD

**Issue by cbl315** [obsidiandynamics/kafdrop#403]
I scan the image `obsidiandynamics/kafdrop:3.30.0`, and find many CVEs to be fixed.

See report:

[obsidiandynamics-kafdrop3300-2022-08-10-030036.pdf](https://github.com/obsidiandynamics/kafdrop/files/9296247/obsidiandynamics-kafdrop3300-2022-08-10-030036.pdf)

**Comment by cbl315** [comment]
Is there a plan about when to release next versoin? I can help with those security issues and hope those issues could be fixed in next release.

**Comment by davideicardi** [comment]
Any help is appreciated! If someone can create a Pull Request explaining the fix I will be happy to merge it.

**Comment by Bert-R** [comment]
@cbl315 Can you share the list of CVE numbers? Just a Fortify scan report isn't very helpful, as Fortify is known to provide very many false positives. The report (the detailed one, not the high-level summary) needs to be interpreted by one who knows both Fortify and the product (Kafdrop) very well.

**Comment by cbl315** [comment]
> @cbl315 Can you share the list of CVE numbers? Just a Fortify scan report isn't very helpful, as Fortify is known to provide very many false positives. The report (the detailed one, not the high-level summary) needs to be interpreted by one who knows both Fortify and the product (Kafdrop) very well.

Sure I can share the CVEs list, btw I use `protecode` as scan tool instead of `fortify`. Unfortunately the scan result of protecode also contains many false positive vulnerabilities, I might try `trivy` also as a reference. 

[obsidiandynamics-kafdrop3300-vulnerabilities.csv](https://github.com/obsidiandynamics/kafdrop/files/9298129/obsidiandynamics-kafdrop3300-vulnerabilities.csv)

**Comment by cbl315** [comment]
Just a curiosity, which security scan tool is used before for kafdrop?

**Comment by cbl315** [comment]
Update: after I replace the base image to the latest release from upstream, the CVEs number has been reduced from 79 to 41. But there are still donzens, I will keep looking and try to check whether they are false positive.

Base image I use to replace: `eclipse-temurin@sha256:555091411bbe4d768d73b9328b1a62bde263fa36f53f49452e2d92a690eb7a2c`. 
[Here](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/11/images/sha256-555091411bbe4d768d73b9328b1a62bde263fa36f53f49452e2d92a690eb7a2c?context=explore) is docker hub url.

New report: [obsidiandynamics-kafdrop3300-vulnerabilities-UpdateBaseImage.csv](https://github.com/obsidiandynamics/kafdrop/files/9305551/obsidiandynamics-kafdrop3300-vulnerabilities-UpdateBaseImage.csv)

**Comment by Bert-R** [comment]
Exactly. That's why I created PR #404.
Note that even though some of the CVEs might be legitimate, it does not at all mean that Kafdrop is vulnerable. The Kafdrop service uses a tiny bit of the capabilities, so it could well be fully safe.

Given the wide use of the Temurin distribution, you should ask yourself whether you should take the responsibility of scanning and analyzing that container image or whether you rely on Adoptium.
