### ISSUE TITLE
Error with SSL auth+encryption: Value of 'env' cannot be null if connecting to secured kafka.

### ISSUE THREAD

**Issue by adivardhan** [obsidiandynamics/kafdrop#41]
I am trying to setup Kafdrop with SSL auth and encryption with brokers.

My Kafka cluster (3 broker are now listening for SSL and PLAINTEXT, for Zookeeper, connections) is now setup with their respective keystore & truststore file.

In Kafdrop, I've placed the same keystore & truststore file in the root dir.

**kafka.properties:**

```
security.protocol=SSL
ssl.endpoint.identification.algorithm=
ssl.truststore.location=/generic-server-truststore.jks
ssl.truststore.password=trustkafka
ssl.keystore.location=/kafka1-server-keystore.jks
ssl.keystore.password=kafkakey
```
**application.yml:**

```
kafka:
  brokerConnect: localhost:9082,localhost:9083,localhost:9084
  isSecured: true
  #saslMechanism: "SASL"
  securityProtocol: "SSL"
  truststoreLocation : "/generic-server-truststore.jks"
  propertiesFileLocation : "/kafka.properties}"
  keystoreLocation : "/kafka1-server-keystore.jks"
```

But, on startup I get the error:
**_Value of 'env' cannot be null if connecting to secured kafka._**

1. Where is the kafka.env property specified?
2. Do we have to specify it? If yes, then why?
3. Why is SASL mandatory? Can I not use SSL for both, Auth & encryption?

Please let me know what I'm doing wrong here.

**Comment by ekoutanov** [comment]
This approach is deprecated. Don't use `isSecured` and `securityProtocol`. It's a Kafdrop 2.x hangover which hasn't yet been ripped out.

See the `README.md` file on how to configure security using the new approach, which works with SASL and SSL.
