### ISSUE TITLE
The getAllTopics API no longer provides offsets

### ISSUE THREAD

**Issue by bmatticus** [obsidiandynamics/kafdrop#424]
One of the recent updates broke the getAllTopics endpoint, it use to provide all the offsets and partition data. I was able to make a quick patch by having that function call the getTopic method and pass in a String[] of all topics from the existing method. This no longer allows a stream as it grabs and does the partition filling before returning, I assume there was a desire to stream this API to make the main page load faster? Maybe an addition to switch the process to fill in all the data with a parameter is the best option?

**Comment by davideicardi** [comment]
From which version do you see this bug?
Can you also try with the version currently in master?

**Comment by bmatticus** [comment]
> From which version do you see this bug?
> Can you also try with the version currently in master?

Fresh build of 3.31.0-SNAPSHOT

If I recall, around line 103 of the KafkaManagerImpl. Once I get back to a computer I’ll get some more details. Wanted to get this out before I forgot.


Edit: https://github.com/obsidiandynamics/kafdrop/blob/e0f84ae58f4f59f3e733af4380c6d03cb3a4e70d/src/main/java/kafdrop/service/KafkaMonitorImpl.java#L102

my quick hack was to call getTopics and pass in the keys from highLevelConsumer.getAllTopics(). Something a little more elegant may be desirable though

**Comment by davideicardi** [comment]
Thank you @bmatticus . And what about v3.30.0?
From that version we have updated a lot of dependencies, I suspect it could be related to that ...

**Comment by bmatticus** [comment]
> Thank you @bmatticus . And what about v3.30.0?
> From that version we have updated a lot of dependencies, I suspect it could be related to that ...

I can take a look and let you know, thanks!

**Comment by bmatticus** [comment]
Went back to 3.28.0 and it works properly, so it appears to have started in 3.29.0. Below is an example of the bad data:

[{"name":"test","partitions":[{"id":0,"replicas":[{"id":1001}],"size":-1,"firstOffset":-1,"leader":{"id":1001},"preferredLeader":{"id":1001},"underReplicated":false,"leaderPreferred":true,"inSyncReplicas":[{"id":1001}],"offlineReplicas":[]},{"id":1,"replicas":[{"id":1001}],"size":-1,"firstOffset":-1,"leader":{"id":1001},"preferredLeader":{"id":1001},"underReplicated":false,"leaderPreferred":true,"inSyncReplicas":[{"id":1001}],"offlineReplicas":[]},{"id":2,"replicas":[{"id":1001}],"size":-1,"firstOffset":-1,"leader":{"id":1001},"preferredLeader":{"id":1001},"underReplicated":false,"leaderPreferred":true,"inSyncReplicas":[{"id":1001}],"offlineReplicas":[]}],"config":{},"preferredReplicaPercent":1.0,"underReplicatedPartitions":[],"availableSize":0,"totalSize":-3}]

See the -3 in the totalSize. I'd have to dig a bit, but on clusters with many topics and millions/billions of offsets I've seen a range of negative values, I'm guessing its adding the partition offsets together and they all default to -1 soemwhere I'm guessing.  Here is what I expect, from 3.28.0:

[{"name":"test","partitions":[{"id":0,"replicas":[{"id":1001}],"size":0,"firstOffset":0,"leader":{"id":1001},"preferredLeader":{"id":1001},"inSyncReplicas":[{"id":1001}],"offlineReplicas":[],"underReplicated":false,"leaderPreferred":true},{"id":1,"replicas":[{"id":1001}],"size":0,"firstOffset":0,"leader":{"id":1001},"preferredLeader":{"id":1001},"inSyncReplicas":[{"id":1001}],"offlineReplicas":[],"underReplicated":false,"leaderPreferred":true},{"id":2,"replicas":[{"id":1001}],"size":3,"firstOffset":0,"leader":{"id":1001},"preferredLeader":{"id":1001},"inSyncReplicas":[{"id":1001}],"offlineReplicas":[],"underReplicated":false,"leaderPreferred":true}],"config":{},"preferredReplicaPercent":1.0,"underReplicatedPartitions":[],"partitionMap":{"0":{"id":0,"replicas":[{"id":1001}],"size":0,"firstOffset":0,"leader":{"id":1001},"preferredLeader":{"id":1001},"inSyncReplicas":[{"id":1001}],"offlineReplicas":[],"underReplicated":false,"leaderPreferred":true},"1":{"id":1,"replicas":[{"id":1001}],"size":0,"firstOffset":0,"leader":{"id":1001},"preferredLeader":{"id":1001},"inSyncReplicas":[{"id":1001}],"offlineReplicas":[],"underReplicated":false,"leaderPreferred":true},"2":{"id":2,"replicas":[{"id":1001}],"size":3,"firstOffset":0,"leader":{"id":1001},"preferredLeader":{"id":1001},"inSyncReplicas":[{"id":1001}],"offlineReplicas":[],"underReplicated":false,"leaderPreferred":true}},"totalSize":3,"availableSize":3}]

**Comment by bmatticus** [comment]
I was thinking maybe something like this:

https://github.com/obsidiandynamics/kafdrop/commit/b579f7f0b9c5740c02b442c5a10fa3d11d72b80e
https://github.com/obsidiandynamics/kafdrop/commit/7242f63f73bc22392d0ffa43b6b46f8fc0d658a4

EDIT: Ignore the /detailed in the first commit, switched to ?details parameter to trigger then full pull of topics with details. Either this or can be a ?streamed to trigger the lighter weight streamed pull that its doing now? I assume on very large clusters that may help with loading the main page.
