### ISSUE TITLE
support arm64 for obsidiandynamics/kafdrop and obsidiandynamics/kafka

### ISSUE THREAD

**Issue by barryzhounb** [obsidiandynamics/kafdrop#443]
Recently I am moving to Macbook with Apple M1 chip, so my previous both kafka docker obsidiandynamics/kafka and kafdrop docker obsidiandynamics/kafdrop didn't work.

Now I am looking for alternative docker images for arm64, for kafdrop, I have found alternative docker, 

```
https://github.com/arm64-compat/kafdrop/pkgs/container/kafdrop
```

But for obsidiandynamics/kafka, do you have any recommended alternative docker image?

**Comment by maksim77** [comment]
I probably don't understand something, but what does M1 have to do with it? I have a kafdrop container running right now on a macbook with such a processor. Yes, this is compatibility mode, but the container still works.
<img width="777" alt="Снимок экрана 2022-11-16 в 23 11 07" src="https://user-images.githubusercontent.com/155911/202284202-a06a1088-dcb5-4bb6-9e48-60a2545a0941.png">
