### ISSUE TITLE
Tests wont run

### ISSUE THREAD

**Issue by shaarif-khan** [obsidiandynamics/kafdrop#461]
I dont know what I am doing wrong, but when I try to run any of the test it is stuck on
"Container confluentinc/cp-kafka:5.4.3 started"
it never run the assert statement.

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/86915411/211398321-61a2e230-ed29-44dd-865c-254a52cf54e9.png">

**Comment by merlin-zaraza** [comment]
@shaarif-khan this is an integration test. Try to increase memory for docker. It works in my env )
