### ISSUE TITLE
Added support for AWS Glue Schema registry

### ISSUE THREAD

**Issue by nicklester** [obsidiandynamics/kafdrop#489]
AWS Glue doesn't use a http endpoint in its configuration, but requires a region and a registry name. AWS client libraries manage the schema registration etc:

https://github.com/awslabs/aws-glue-schema-registry

WIP PR. Any thoughts?

https://github.com/obsidiandynamics/kafdrop/pull/488

**Comment by Bert-R** [comment]
@nicklester Do you plan to complete the PR you started?

**Comment by nicklester** [comment]
Hi,

I'll be on it next week - day job took over a bit. Hope that's ok?

**Comment by Bert-R** [comment]
@nicklester Still interested in taking this forward?

**Comment by nicklester** [comment]
Hi Bert,

I'll be on this in a week or so - appreciate the waiting on this. We still
need the feature!

Cheers for patience!

**Comment by vl-kp** [comment]
any update?
