### ISSUE TITLE
Allow connecting to a secured Kafka cluster (SSL) with client authentication

### ISSUE THREAD

**Issue by teebee** [obsidiandynamics/kafdrop#5]
I may miss something, but it seems that connecting to a secured Kafka cluster (SSL) with client authentication is currently not supported. Could you provide a corresponding configuration option, please?

**Comment by ekoutanov** [comment]
The current support for authentication is pretty abysmal. I believe the only thing we have is SASL support.

We'll probably have to make changes to `KafkaHighLevelConsumer` to specify (I assume) a keystore, and have that externally configurable.... And also have to think how we make it configurable in a Docker environment (perhaps via a volume mount).

**Comment by ekoutanov** [comment]
@teebee I've done a bunch of changes to support SASL and TLS, described [here](https://github.com/obsidiandynamics/kafdrop/pull/30). It provides a lot more flexibility than the current approach. The old way will still work, but should be considered deprecated. Ideally you should try to get off it as soon as possible.
