### ISSUE TITLE
Generate new ASCII art for Kafdrop 4

### ISSUE THREAD

**Issue by Bert-R** [obsidiandynamics/kafdrop#503]
Now that the major version number is incremented, we need new ASCII art in [``kafdrop.sh``](https://github.com/obsidiandynamics/kafdrop/blob/master/src/main/docker/kafdrop.sh).

**Comment by randr97** [comment]
Hi @Bert-R - Would be great if you take a look at this PR - https://github.com/obsidiandynamics/kafdrop/pull/524
This is my 1st contribution to this repo and look forward to taking up bigger issues as and when I get a hang of this repo.
Cheers!

**Comment by randr97** [comment]
@Bert-R made a bunch of changes and have put in a new PR
- Last time I had manually changed it without auto-generation
- Website used to generate the text - https://patorjk.com/software/taag/#p=display&f=Alligator2&t=KAFDROP%204
