### ISSUE TITLE
Usage of "Github Star" in Kafdrop web UI

### ISSUE THREAD

**Issue by mikmatko** [obsidiandynamics/kafdrop#52]
I was surprised to see that Kafdrop attempts to connect to the public Internet. It seems to be accessing the Github Star thing via HTTP call.

Is there a reason for keeping this as part of the web UI? To me it seems a red flag. The nature of Kafdrop is to serve as an "Admin UI" for Kafka. This means that for any serious production usage, it shouldn't be attempting to connect to the public Internet at all.

Please consider removing this functionality.

**Comment by ekoutanov** [comment]
Fixed.

**Comment by ekoutanov** [comment]
Released in 3.18.1

**Comment by knokio** [comment]
In that case you probably don't need to include `js/github-buttons.js` with the project. What do you think @ekoutanov @mikmatko ?

**Comment by ekoutanov** [comment]
Would happily replace with a simple icon (hyperlinked) to mimic current behaviour.
