### ISSUE TITLE
The /github subscribe [repository name] Command Fails To Subscribe

### ISSUE THREAD

**Issue by arunmalve** [obsidiandynamics/kafdrop#520]
The GitHub app returns the following message when using the `/github subscribe obsidiandynamics/kafdrop`

Error Message:
"Either the app isn't installed on your repository or the repository does not exist. Install it to proceed." despite supplying a valid repo URL and having already installed the GitHub app on the Slack Workspace.

Please install the Slack app to see the new release notifications.

**Comment by davideicardi** [comment]
I don't think this is related to kafdrop, it sounds to be a problem with Slack integration.
Can you try for example with another repository?

Closing the issue for now, feel free to re-open it in case you think there is something wrong with kafdrop.

**Comment by arunmalve** [comment]
This is a reference link to the Slack integration in the Repo for notifications to be installed, so we can easily follow any new `Releases`. [davideicardi](https://github.com/davideicardi)
https://www.youtube.com/watch?v=pB_nmvjYGQM

thank you so much for your attention and participation.
