### ISSUE TITLE
The /github subscribe [repository name] Command Fails To Subscribe

### ISSUE THREAD

**Issue by arunmalve** [obsidiandynamics/kafdrop#536]
The GitHub app returns the following message when using the `/github subscribe obsidiandynamics/kafdrop`

Error Message:
"Either the app isn't installed on your repository or the repository does not exist. Install it to proceed." despite supplying a valid repo URL and having already installed the GitHub app on the Slack Workspace.

Please install the Slack app to see the new release notifications.

reference to this link - https://github.com/obsidiandynamics/kafdrop/issues/520

**The solution to implement:**
This is a reference link to the Slack integration in the Repo for notifications to be installed, so we can easily follow any new Releases. [davideicardi](https://github.com/davideicardi)
https://www.youtube.com/watch?v=pB_nmvjYGQM

thank you so much for your attention and participation.

**Comment by davideicardi** [comment]
This looks like some sort of configuration problem. I don't think it is related to kafdrop. Does it work for other repositories?
Maybe you should put the full url
```
/github subscribe https://github.com/obsidiandynamics/kafdrop
```
?

**Comment by arunmalve** [comment]
Nope, this is not working for the above-mentioned command in Slack. `/github subscribe https://github.com/obsidiandynamics/kafdrop`

`Error Message:`
"Either the app isn't installed on your repository or the repository does not exist. Install it to proceed." despite supplying a valid repo URL and having already installed the GitHub app on the Slack Workspace.

If you could help follow this link to update the Slack app to be installed in Repo - 
youtube reference link to add slack app - https://www.youtube.com/watch?v=pB_nmvjYGQM

**Comment by Bert-R** [comment]
That's what I would expect indeed, as the app isn't installed.
@davideicardi  Personally, I'm not in favor of adding the app as we as maintainers do not use it. IMHO, the mail notification of GitHub is good enough for people out side the team.

**Comment by davideicardi** [comment]
Yes, I agree @Bert-R . Maybe @arunmalve you can use the Slack RSS integration has suggested here: https://github.com/integrations/slack/issues/454#issuecomment-1582472473
