### ISSUE TITLE
ACL empty

### ISSUE THREAD

**Issue by iboumedien** [obsidiandynamics/kafdrop#55]
Hi thanks for this awesome tool.  Can you tell me what configuration I should have to use ACL page. 
Wish a reply.

Best regards
Ismael

**Comment by ekoutanov** [comment]
@iboumedien  You need security enabled in the broker before the ACL page will show any entries. This can be done by setting up SASL. Have a look at Confluent's [Security 101](https://www.confluent.io/blog/apache-kafka-security-authorization-authentication-encryption/) article.
