### ISSUE TITLE
Kafka and kafdrop connection query

### ISSUE THREAD

**Issue by shekhar098** [obsidiandynamics/kafdrop#56]
I have separate Kafka server. how I will connect the kafdrop with kafka. I have downloaded Kafka from 'https://kafka.apache.org/'. And zookeeper and kafka is running sperate. I am beginner any help is appreciated

**Comment by ekoutanov** [comment]
Run the Kafdrop jar file with the following argument:
```
--kafka.brokerConnect=host:port
```

Where `host:port` point to your broker, presumably `localhost:9092` if you are running locally.

If you're a noon and want a gentle introduction to Kafka and Kafdrop, have a read of this [article](https://medium.com/swlh/introduction-to-event-streaming-with-kafka-and-kafdrop-22afdb4b380a)

**Comment by shekhar098** [comment]
Thanks @ekoutanov. I have connected all things properly and it's working fine. I really appreciate your help. I have one more query. Is there any graph feature or  some other plugin that connect with kafdrop for graph feature ?

**Comment by ekoutanov** [comment]
No worries. I'm glad you liked it. Don't forget to  ⭐️the project :)

As for graphs, not at this stage. If you want graphing, you are better off with a metrics scraper (like prometheus+grafana). Perhaps one day we can add graphs into Kafdrop, but this hasn't been a priority.

**Comment by shekhar098** [comment]
Thanks :)
