### ISSUE TITLE
Unable to disable vulnerable TLS protocols TLSv1, TLSv1.0

### ISSUE THREAD

**Issue by abhishek852008** [obsidiandynamics/kafdrop#564]
Though readme says we can control protocol versions. I am setting _ssl.enabled.protocols=TLSv1.2,TLSv1.3_ in kafka.properties file, still its not stopping connection with lower protocols. Testing with _openssl s_client -connect server:port -tls1_

kafka.properties: specifying the necessary configuration, including key/truststore passwords, cipher suites, **enabled TLS protocol versions**, username/password pairs, etc.

Let me know how can i disable those lower protocols. Using latest stable version 3.31.0.

**Comment by reneleonhardt** [comment]
Did you double-check that your configuration has been accepted, maybe by disabling a setting?
https://stackoverflow.com/questions/52418180/disable-tls-1-0-tls-1-1-in-apache-kafka
https://docs.confluent.io/platform/current/kafka/authentication_ssl.html

Did you configure related settings?
* security.protocol=SSL
* ssl.protocol=TLSv1.3
* ssl.client.auth=required
* advertised.listeners
https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html

I would allow only those cipher suites, which are recommended for TLSv1.2 and 1.3 (unfortunately I could only find a German list, but you can just copy the names to `ssl.cipher.suites`):
https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102-2.pdf

**Comment by abhishek852008** [comment]
Yes, I had tried all those but nothing works.
I suspect kafdrop jar is not reading and applying kafka.properties file fully.
I had to provide following JVM option myself to jar to make it work-

-Dserver.ssl.enabled-protocols=TLSv1.2,TLSv1.3

I had tried below as well, but actually not needed-
-Djdk.tls.disabledAlgorithms=SSL,SSLv2,SSLv3,TLSv1,TLSv1.1

Thanks! Closing it.

**Comment by abhishek852008** [comment]
Yes, I had tried all those but nothing works.
I suspect kafdrop jar is not reading and applying kafka.properties file fully.
I had to provide following JVM option myself to jar to make it work-

-Dserver.ssl.enabled-protocols=TLSv1.2,TLSv1.3

I had tried below as well, but actually not needed-
-Djdk.tls.disabledAlgorithms=SSL,SSLv2,SSLv3,TLSv1,TLSv1.1

Thanks! Closing it.
