### ISSUE TITLE
Please help create new release & image

### ISSUE THREAD

**Issue by Nishtha1994** [obsidiandynamics/kafdrop#569]
The 3.31.0 tag and image has a number of high and critical security vulnerabilities (39). Please update the dependency stack and push a new version. A number of commits have been made since the last version

<img width="1292" alt="Screenshot 2023-09-20 at 12 13 32 AM" src="https://github.com/obsidiandynamics/kafdrop/assets/24848971/b6d7684a-3664-48c3-82c8-902569cce877">
<img width="1728" alt="Screenshot 2023-09-20 at 12 13 57 AM" src="https://github.com/obsidiandynamics/kafdrop/assets/24848971/c841992d-7801-44d0-b1dc-e5d9fa878251">

**Comment by Bert-R** [comment]
@davideicardi How do we handle this?

**Comment by davideicardi** [comment]
I will release a new version in the following days!

**Comment by davideicardi** [comment]
Release 4.0.0 just published!
