### ISSUE TITLE
Can I disable the topic creation 

### ISSUE THREAD

**Issue by senthil13** [obsidiandynamics/kafdrop#59]
Hi, 
How can i disable/ enable the topic creation ?

**Comment by ekoutanov** [comment]
It's always enabled.

**Comment by senthil13** [comment]
so we cant run it like a read-only ?

**Comment by ekoutanov** [comment]
No, it's not configurable.
If you need to run Kafdrop in an environment where topic creation needs to be disabled, then you should run Kafdrop with a dedicated user with read-only ACLs. Then the form will still be available, but trying to create a topic will result in an error.
Alternatively, you can fork and make topic creation configurable. (e.g. `topicCreationEnabled=false`) Then submit a PR.

**Comment by senthil13** [comment]
Thanks for info, i evaluate which route is suitable for us and implement the same.

**Comment by ahmadshakil** [comment]
Tried user with read only access but got this error 

kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [Topic authorization failed.]

So cant even view topics

**Comment by calebickler** [comment]
ran into the same problem, I don't have the access to create topics but I still want to browse

**Comment by ahmadshakil** [comment]
I did change in kafdrop.service.KafkaMonitorImpl class method getTopicMetadata and added a try catch to make it work

so the method structure is now
final var topicInfos = highLevelConsumer.getTopicInfos(topics);
final var retrievedTopicNames = topicInfos.keySet();
try{
}
  ......
}
catch (KafkaAdminClientException exc) {
			LOG.warn("Ignoring KafkaAdminClientException in highLevelAdminClient.describeTopicConfigs. This require write ACL enabled on topics");
}
		return topicInfos;

**Comment by calebickler** [comment]
Did that work? is there a PR?

**Comment by ahmadshakil** [comment]
Yes it worked form me but I did change on local here is change request  but I guess it is not incorporated

https://github.com/obsidiandynamics/kafdrop/pull/88

**Comment by yychy** [comment]
@ahmadshakil, Thanks for your info and disable topic creation is very important for us. Today, I used latest docker image to install kafdrop with a dedicated user with read-only ACLs and I got the same error "org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [Topic authorization failed.]". It looks like the fix is not in latest docker image yet. Do you know when the new image will be built for the fix?

**Comment by calebickler** [comment]
That fix ain't going in, someone needs to open a PR where you can pass in a env variable for disable topic creation and skip the erroring code.
> Alternatively, you can fork and make topic creation configurable. (e.g. topicCreationEnabled=false) Then submit a PR.
