### ISSUE TITLE
When running kafdrop in a separate container, I can't configure the kafka broker address.

### ISSUE THREAD

**Issue by AlekseyS2877** [obsidiandynamics/kafdrop#598]
Hey, everybody.
The developers asked me to install kafdrop for them in a separate Docker container on the server with Ubuntu 22, Docker version 24.0.7, build afdd53b.
The first thing I did was to check if kafka was working, for that I used kafakcat.

After that I took a part of your docker-compose file, the part that deals directly with kafdrop.
```
version: "2"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "s.kafka:9093"
```
but it didn't work out.
Everything is assembled and running, but in the logs of the container writes that it can not connect to the broker at the address localhost/127.0.0.0.1:9093 and eventually crashes. Inside the container, the environment variable is set correctly.
I try IP adresses, create DNS aliases, but it's not working... I try to add command args to docker-compose file "--kafka.brokerConnect=s.kafka:9093" and in "docker ps" i can see that the start command in the container has changed. But it's not working...
Well if it needs localhost so much and kafka and kafdrop are installed on the same server I used the container home networking mode and everything worked.
But if tomorrow they tell me to put them on different servers I don't know what I'll do.....
The strangest thing is that once out of dozens of attempts to rebuild the container with different parameters kafdrop picked up the IP specified in the variable, but by the law of meanness, just this time I made a typo in the address subnet I have 2, and I entered 1....
Upd1:
We don't use kubernetes, helm, charts,...

Upd2: 
Sorry to disturb you!
Unfortunately I didn't immediately check the settings of kafka itself....
After multiple attempts to configure, build from source, manually build containers, etc., I decided to check what settings kafka runs with. 
And found that Kafka starts with KAFKA_ADVERTISED_LISTENERS pointing to localhost:9093
That's why kafdrop couldn't connect to kafka. As I understand: kafdrop connected to bootstrap server s.kafka:9093, received from it the broker address localhost:9093 and of course could not connect to it. Anyway, after configuring kafka correctly, the problem went away. Kafdrop works normally.
Maybe this situation will help someone in setting up kafka and kafdrop.

**Comment by acheng-floyd** [comment]
It helps ,i have the same problems, thanks for your share

**Comment by AlekseyS2877** [comment]
That's great!
