### ISSUE TITLE
Avro deserializer looking in /topic instead of /subjects

### ISSUE THREAD

**Issue by jeffworne** [obsidiandynamics/kafdrop#60]
Hello,

I'm getting the following error message when trying to use our Avro registry server
`UT005023: Exception handling request to /topic/events.jobs.errors/messages`

I can make `curl` requests against our schema registry and I get valid JSON, but the path is under `/subjects/events/jobs/errors` and not `/topic/events.jobs.errors/messages`.

```
curl -X GET -i -H "Content-Type: application/vnd.schemaregistry.v1+json" http://[machine]:[port]/subjects/events/jobs/errors
HTTP/1.1 200 OK
Server: gunicorn/20.0.0
Date: Thu, 19 Dec 2019 22:26:40 GMT
Connection: close
Content-Type: application/json
Content-Length: 70

{"specs": ["fpe", "memory", "segfault", "si"], "version"...}
```

Am I missing a configuration setting for Kafdrop? I did not configure our Avro installation, so I'm a bit hamstrung with how it currently works.

**Comment by ekoutanov** [comment]
I believe it's just the default behaviour of the library. Not sure if it's configurable.

**Comment by jeffworne** [comment]
I see. We might try making a softlink in the expected location to the current schema in our custom folder. If you happen to see a way to do this in the library, that would be helpful!

**Comment by ekoutanov** [comment]
@jeffworne did that help?

**Comment by jeffworne** [comment]
We ended up making our own internal topic browser to handle regular and Avro encoded topics, since it seemed like a bit too much work to tinker with the links. However, our internal interface isn't as nice as Kafdrop, so I'm still using it for standard topics.

**Comment by ekoutanov** [comment]
Ok thanks. Would it be hard to get this fix in Kafdrop you think?

**Comment by jeffworne** [comment]
I'm not completely sure about the implementation here (I don't have access to the source code) but I suspect we used the bare minimum Avro APIs to access the schema registry (so we weren't confined to a default path) and then wrote the rest to handle the decoding. Without digging further into the Avro library you're using, I'm not sure how challenging it would be to make the schema path configurable.

**Comment by ekoutanov** [comment]
Ok thanks.
