### ISSUE TITLE
Is there any way to hide the messages from kafdrop as in PROD it is not suitable to show the messages of eventhub or kafka

### ISSUE THREAD

**Issue by yogeshgoel001** [obsidiandynamics/kafdrop#612]
Is there any way to hide the messages from kafdrop as in PROD it is not suitable to show the messages of eventhub or kafka

**Comment by Bert-R** [comment]
Can you be more specific? The purpose of Kafdrop is to look into Kakfa, so your request sounds like the opposite of the purpose. What about not running Kafdrop in PROD?

**Comment by yogeshgoel001** [comment]
Kafdrop has feature to Browse the messages for kafka/eventhub which is good for NON PROD environment, but for PROD we can have PCI/NON PCI data as well, which should not be visible to anyone even internally. So is there any way to hide the messages on Kafdrop UI for topics.

**Comment by Bert-R** [comment]
So you want to browse the topics, etc. but not the message content. There is no configuration option for that, but you might be able to accomplish what you want by running Kafdrop behind Nginx, with a specific configuration that blocks access to the messages.

The README describes how to run Kafdrop behind Nginx, but you would need to figure out what paths to block to prevent access to the messages. The OpenAPI specification would be helpful for that.
