### ISSUE TITLE
arm64 architecture

### ISSUE THREAD

**Issue by dlipofsky** [obsidiandynamics/kafdrop#627]
Looking on hub.docker.com I see `linux/amd64` but not `linux/arm64`. We're wanting to run on AWS Graviton nodes (ARM) for cost savings, and all the 3rd party images we use except this one provide both architectures. Would it be possible for you to provide both to docker hub? Thank you!

**Comment by Bert-R** [comment]
We currently do not have the bandwidth to do this, but we welcome a PR for it.

**Comment by rtammekivi** [comment]
Some older versions are available here, maybe it can be used as a reference: https://github.com/arm64-compat/kafdrop/pkgs/container/kafdrop

**Comment by rtammekivi** [comment]
I decided to take a whack at it. https://github.com/obsidiandynamics/kafdrop/pull/672
