### ISSUE TITLE
Incorrectly connecting to Zookeer at localhost

### ISSUE THREAD

**Issue by sorvis** [obsidiandynamics/kafdrop#63]
Hello,

I'm trying this out against one of our environments kafka clusters using docker:
`winpty docker run -it --rm -p 9002:9000     -e KAFKA_BROKERCONNECT=x.x.x.11:6667,x.x.x.12:6667     -e JVM_OPTS="-Xms32M -Xmx64M"     obsidiandynamics/kafdrop:latest`

I'm seeing it start then try connecting to Zookeeper at localhost in a constant loop:

> 2020-01-03 19:05:21.636  INFO 15 [           main] o.a.z.Environment                        : Client environment:os.memory.total=49MB
> 2020-01-03 19:05:21.647  INFO 15 [           main] o.a.z.ZooKeeper                          : Initiating client connection, connectString=localhost:2181 sessionTimeout=5000 watcher=org.apache.curator.ConnectionState@781711b7
> 2020-01-03 19:05:21.686  INFO 15 [           main] o.a.z.c.X509Util                         : Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
> 2020-01-03 19:05:21.709  INFO 15 [           main] o.a.z.ClientCnxnSocket                   : jute.maxbuffer value is 4194304 Bytes
> 2020-01-03 19:05:21.738  INFO 15 [           main] o.a.z.ClientCnxn                         : zookeeper.request.timeout value is 0. feature enabled=
> 2020-01-03 19:05:21.801  INFO 15 [localhost:2181)] o.a.z.ClientCnxn$SendThread              : Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
> 2020-01-03 19:05:21.834  INFO 15 [localhost:2181)] o.a.z.ClientCnxn$SendThread              : Socket error occurred: localhost/127.0.0.1:2181: Connection refused
> 2020-01-03 19:05:22.170  INFO 15 [           main] k.s.BuildInfo                            : Kafdrop version: 3.9.0, build time: 2019-09-26T09:17:02.688Z

Is localhost a default for the Zookeeper server someplace? I tried searching through the code, but I don't see where it might be hard coded.

**Comment by ekoutanov** [comment]
This doesn't look right
Kafdrop removed ZK support a few months ago. Your docker is probably caching an old image. Can you do 'docker pull obsidiandynamics/kafdrop'

**Comment by sorvis** [comment]
@ekoutanov Ahh, it seems you are right I must have cached an older version from way back when. I ran this and got the service to start:

> obsidiandynamics/kafdrop:3.19.0

I'm still hitting another issue:

> org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_CONFIGS

I suspect that more so has to do with my kafka version not playing nice. I'll let you close the ticket out unless you think something else is at play.

Thank you very much for the help!

**Comment by ekoutanov** [comment]
Which version of Kafka are you running?

**Comment by sorvis** [comment]
Our kafka version is:  0.10.1

**Comment by ekoutanov** [comment]
I believe you'll need at least 0.11

**Comment by sorvis** [comment]
That explains it then. Thank you for the help!
