### ISSUE TITLE
The Search Messages functionality generates very often the error message for illegal format

### ISSUE THREAD

**Issue by dj-mister** [obsidiandynamics/kafdrop#649]
Hi all,

Below is the stack snapshot:

A 500 error has occurred: Request processing failed: java.util.IllegalFormatConversionException: d != java.util.Date
Stack trace
java.util.IllegalFormatConversionException: d != java.util.Date at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4442) at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2963) at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2918) at java.base/java.util.Formatter.format(Formatter.java:2689) at java.base/java.util.Formatter.format(Formatter.java:2625) at java.base/java.lang.String.format(String.java:4145) at kafdrop.service.KafkaMonitorImpl.searchMessages(KafkaMonitorImpl.java:282) at kafdrop.controller.MessageController.searchMessageForm(MessageController.java:247) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at

One of the possible reason, the search pattern contains exactly date numbers without timezone postfix, but the real date in message has the next format:
"@timestamp":"2024-06-08T07:54:26.627**Z**"

Regards,
Yuri

**Comment by Savageman** [comment]
It is fixed already: https://github.com/obsidiandynamics/kafdrop/pull/601
However the latest tag is from November 2nd 2023 (7 months ago). We need a new release to benefit from the improvements!
