### ISSUE TITLE
where is Dockerfile?

### ISSUE THREAD

**Issue by chinaboy007** [obsidiandynamics/kafdrop#650]
I want to build arrch64 system docker images, but not fond it. please tell me where is Dockerfile, Thanks!

**Comment by Bert-R** [comment]
I bet you didn't spend long searching for it. It's in a rather obvious location: [`src/main/docker/Dockerfile`](https://github.com/obsidiandynamics/kafdrop/blob/master/src/main/docker/Dockerfile).
