### ISSUE TITLE
Wrong initial key format in "Search Message" gui

### ISSUE THREAD

**Issue by beck2play** [obsidiandynamics/kafdrop#659]
The "Search Message" gui uses the `defaultFormat` as initial value for "Key format" instead of `defaultKeyFormat`.

Replacing `defaultForm.setKeyFormat(defaultFormat)` with `defaultForm.setKeyFormat(defaultKeyFormat)` in `MessageController.java` should fix it.

Note: I never contributed to public repository on github. I have not been able to push the fix on a new branch to open a pull requst. I am not sure if I made a mistake or if one needs to be granted specific rights. Help would be appreciated.

**Comment by Bert-R** [comment]
@beck2play Thanks for reporting and providing the fix! I've created a PR.
