### ISSUE TITLE
No support for schema reg & message format in docker env vars

### ISSUE THREAD

**Issue by markl11** [obsidiandynamics/kafdrop#66]
Hi, please could you add support for schema registry and message format (AVRO) in the environment variables of the docker image?

**Comment by ekoutanov** [comment]
I'm a bit snowed under at the moment; would you like to submit a PR? The change should be quite simple.

**Comment by leohoare** [comment]
I was setting them through CMD_ARGS and doesn't appear to work, from the DockerFile this appears like to should be passed through?
e.g. -e CMD_ARGS="--message.format=AVRO --schemaregistry.connect=https://url:8082"
Doesn't appear to be defaulting the message format either, is this expecting or is it an incorrect configuration on my end? As there is a protobuf example using a similar methodology.

**Comment by BryceSchmitt** [comment]
Passing in those same CMD_ARGS into Docker worked for me. Try using http for the schema registry url rather than https; the registry might not be setup to use https.

**Comment by leohoare** [comment]
Thanks @BryceSchmitt , It's potentially as the container is running on Fargate but I'm unsure how this would affect the container as it should set the environment variable with the similar logic. https is a requirement, so http isn't a workaround 😢.
https://github.com/obsidiandynamics/kafdrop/issues/24

I tried with setting the environment SCHEMAREGISTRY_CONNECT and the schema registry appears to be picked up (schema.registry.url isn't null), in the future I'd use this and it might be worth updating the docs for this (a bit more usable). 
In terms of truststore does it use the same truststore (KAFKA_TRUSTSTORE) as it's not locating the cert in the ssl handshake?

@ekoutanov , loving all the hard work! Great project and all the effort really shows ⭐️
I'm also Sydney based, should grab a coffee sometime ☕️

**Comment by ekoutanov** [comment]
Guys, if you want to update the `README.md` — by all means, shoot a PR through.
