### ISSUE TITLE
Usability issue when creating a new topic

### ISSUE THREAD

**Issue by da-amit-mujawar** [obsidiandynamics/kafdrop#690]
Creating a new topic button is placed at the bottom of the topic list.
When we have hundreds of topics, this list keeps loading and page keeps scrolling. It is almost impossible to see the button and click to start creating a topic without eternal wait to let the loading and scrolling finish.

Suggestions: (1) have this create button on top of the list (2) have pagination for topic list to avoid loading all topics in single shot (3) keep the list in a scrollable div with a fixed height and add the action button at the bottom of this scrollable div so that it is always visible - let the scrolling div keep loading more topics as it gets from backend

**Comment by Bert-R** [comment]
We currently do not have time to fulfil this request, but  you are welcome to create a PR for it. We will review and merge it in the coming months.
