### ISSUE TITLE
docker run obsidiandynamics/kafdrop:4.0.3-SNAPSHOT

### ISSUE THREAD

**Issue by justin-zc** [obsidiandynamics/kafdrop#707]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by Bert-R** [comment]
Looks like you pulled the wrong platform. The snapshot build (and future releases) support two platforms ARM64 and AMD64. To run the ARM64 version, add this option to your `docker run` command: `--platform linux/arm64`.

**Comment by justin-zc** [comment]
> Looks like you pulled the wrong platform. The snapshot build (and future releases) support two platforms ARM64 and AMD64. To run the ARM64 version, add this option to your `docker run` command: `--platform linux/arm64`.

Thank you for clarifying! I’ll update the command with --platform linux/arm64 to ensure the correct platform is used. Appreciate the heads-up!
