### ISSUE TITLE
kafdrop.sh does not work with blanks in base64 property-strings

### ISSUE THREAD

**Issue by juergenhemelt** [obsidiandynamics/kafdrop#72]
When the base64 coded values for KAFKA_PROPERTIES, KAFKA_TRUSTSTORE and KAFKA_KEYSTORE contain blanks, the decoding in the script does not work. Environment variables should be put in double quotes in kafdrop.sh.

**Comment by ekoutanov** [comment]
Hmm... Under what circumstances would b64-encoded values contain whitespaces?

**Comment by juergenhemelt** [comment]
Seems that the problem is the "echo" statement. Without "echo" base64 generates multiple lines whilst with "echo" the lines are concatenated and separated by a whitespace:

cat /tmp/kafka.properties | base64

c2VjdXJpdHkucHJvdG9jb2w9U1NMCnNzbC50cnVzdHN0b3JlLmxvY2F0aW9uPS90bXAvcmVwbmVz
dC1rYWZrYS5yZXBuZXN0LWV0dS5jbGllbnQudHJ1c3RzdG9yZS5qa3MKc3NsLnRydXN0c3RvcmUu
cGFzc3dvcmQ9Y2hhbmdlaXQKc3NsLmtleXN0b3JlLmxvY2F0aW9uPS90bXAvcmVwbmVzdC1rYWZr
YS5yZXBuZXN0LWV0dS5jbGllbnQua2V5c3RvcmUuamtzCnNzbC5rZXlzdG9yZS5wYXNzd29yZD1j
aGFuZ2VpdAo=

echo $(cat /tmp/kafka.properties | base64)

c2VjdXJpdHkucHJvdG9jb2w9U1NMCnNzbC50cnVzdHN0b3JlLmxvY2F0aW9uPS90bXAvcmVwbmVz dC1rYWZrYS5yZXBuZXN0LWV0dS5jbGllbnQudHJ1c3RzdG9yZS5qa3MKc3NsLnRydXN0c3RvcmUu cGFzc3dvcmQ9Y2hhbmdlaXQKc3NsLmtleXN0b3JlLmxvY2F0aW9uPS90bXAvcmVwbmVzdC1rYWZr YS5yZXBuZXN0LWV0dS5jbGllbnQua2V5c3RvcmUuamtzCnNzbC5rZXlzdG9yZS5wYXNzd29yZD1j aGFuZ2VpdAo=

**Comment by juergenhemelt** [comment]
It's not the echo but the command substitution $(..): see the bash-manpage:
...
Embedded newlines are not deleted, but they may be removed during word splitting.
...
If the substitution appears within double quotes, word splitting and pathname expansion are not performed on the results.

**Comment by ekoutanov** [comment]
That's interesting. I'm not able to reproduce this. What OS and shell are you running?

**Comment by juergenhemelt** [comment]
I'm on Ubuntu 18.04. and running a bash-shell.

**Comment by ekoutanov** [comment]
I think this might have been fixed by https://github.com/obsidiandynamics/kafdrop/pull/74.

**Comment by juergenhemelt** [comment]
Yes that's it.
