### ISSUE TITLE
Kafdrop recreates deleted topics in dockerized Kafka

### ISSUE THREAD

**Issue by jeffworne** [obsidiandynamics/kafdrop#77]
Hello,

I've noticed a strange issue with Kafdrop and Kafka Docker. When I remove my Kafka Docker volumes and create a new instance, I can confirm that I have no topics.
```
bash-4.4# $KAFKA_HOME/bin/kafka-topics.sh --zookeeper <zk_ip>:2181 --list
bash-4.4#
```

However, when I refresh Kafdrop, I see these messages in the Kafka Docker log.
```
kafka_1      | [2020-02-04 00:17:09,798] INFO Creating topic single_partition with configuration {} and initial partition assignment Map(0 -> ArrayBuffer(1001)) (kafka.zk.AdminZkClient)
zookeeper_1  | 2020-02-04 00:17:09,801 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@653] - Got user-level KeeperException when processing sessionid:0x100794dd0cf0000 type:setData cxid:0x40 zxid:0x20 txntype:-1 reqpath:n/a Error Path:/config/topics/single_partition Error:KeeperErrorCode = NoNode for /config/topics/single_partition
kafka_1      | [2020-02-04 00:17:09,840] INFO [KafkaApi-1001] Auto creation of topic single_partition with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
```

```
bash-4.4# $KAFKA_HOME/bin/kafka-topics.sh --zookeeper <zk_ip>:2181 --list
single_partition
```

I originally made the `single_partition` topic via command-line and now it's continuing to persist whenever I refresh Kafdrop. I also tried to load Kafdrop in a private browsing window (thinking there was some cacheing or similar) but that didn't fix the observed behavior.

**Comment by ekoutanov** [comment]
This is not a Kafdrop issue and nothing to do with caching. Kafka's default behaviour is to auto-create topics when you are trying to publish to it, consume from it, or even fetch metadata. So when you are refreshing Kafdrop, it sends a query to Kafka, which creates the topic.
To disable, set `auto.create.topics.enable` to `false` on the broker.

**Comment by jeffworne** [comment]
Hi,

I restarted Kafdrop and the topic is now not automatically created. I guess there's no way to have Kafdrop know that a topic doesn't exist anymore without it querying Kafka, which then creates the topic again (chicken-and-egg problem).

In any case, thanks for the explanation.
