### ISSUE TITLE
Allow to view all messages from topic at once.

### ISSUE THREAD

**Issue by amburin** [obsidiandynamics/kafdrop#8]
Now it is difficult to track last received message but with ablility to view all messages from topic at once it will be much easier.

**Comment by artyomsv** [comment]
Maybe it is just better to show the latest messages at the top of the list?

**Comment by shaaimin** [comment]
Maximum number of records from once query had been set to 100 now,
so if you want to view the latest messages, you should adjust the parameter of Offset which is the start position of query. you can saw it on the UI.

**Comment by shaaimin** [comment]
@ekoutanov 
i think using a pagination is better to view messages than adjust the parameter of Offset manually.

**Comment by ekoutanov** [comment]
Agreed @shaaimin. 
But this ticket is dealing with a slightly different concern. It's about viewing messages across all partitions in a topic, rather than for one partition.

**Comment by shaaimin** [comment]
@ekoutanov 
I see. so the option for "all" also can be selected from Partition options maybe needed.

**Comment by ctrongduc** [comment]
has anyone been working on this yet? I'm thinking to attempt to implement this feature.

**Comment by ekoutanov** [comment]
Not really. Go ahead. It's basically same code as reading from one partition, but done across multiple partitions simultaneously.
There's some trickery in the handling of timeouts, etc, which you'll see done in the current code.

**Comment by ctrongduc** [comment]
Thanks for the tip, I'm start working on the code.

**Comment by Wouter86** [comment]
It's sort of implemented as part of my pull request. Get it as soon as it's accepted or fetch the fork from my github account.

The feature allows to fetch the latest messages of a topic, limited by the given count per partition (<=99999/partition). You just have to select the partition "any" and specify a count. Start offset is ignored. Results are returned in descending timestamp order.

**Comment by ekoutanov** [comment]
The PR raised by @Wouter86 does not completely address this ticket.

@ctrongduc How are you getting on with this?

**Comment by ctrongduc** [comment]
@ekoutanov I'm still working on this, will try to get PR this weekend

**Comment by ctrongduc** [comment]
@ekoutanov my first attempt to address this ticket in PR#145. 
Please review and let me know if I'm in the right the direction, I'm eager to fix anything that not quite right. Pulling message using multiple threads are in pipeline as well.

**Comment by mario45211** [comment]
bump
