### ISSUE TITLE
User ACL Permission Level

### ISSUE THREAD

**Issue by KhoiDinh** [obsidiandynamics/kafdrop#80]
To start up kafdrop, what is the level of permission does a user need to do? I see that a user who is added with the --cluster option can do so but a user with consume & produce permissions for all topics can't. Can someone advise?

**Comment by ekoutanov** [comment]
When Kafdrop can't invoke some operation on the cluster due to a permission violation, it will typically print an exception in the log. You can then add these permissions to the Kafka user.
Ideally the Kafka user should have 'describe' permissions.
