### ISSUE TITLE
Container are crashing in kubernetes

### ISSUE THREAD

**Issue by ss1796** [obsidiandynamics/kafdrop#84]
Running something the following for helm install
helm upgrade -i kafdrop chart --set image.tag=latest  --set kafka.brokerConnect="<kafka-brokers>" --set kafka.properties="$(cat kafka.properties | base64)" --set kafka.truststore="$(cat kafka.truststore.jks | base64)" --set kafka.keystore="$(cat kafka.keystore.jks | base64)"

Kubernetes pods are getting created but it crashes
NAME                       READY   STATUS             RESTARTS   AGE
kafdrop-6f6f6f8859-j7tk5   0/1     CrashLoopBackOff   12         40m
kafdrop-f867d5778-6qhm6    0/1     CrashLoopBackOff   12         40m

when I look at the logs I see
standard_init_linux.go:207: exec user process caused "argument list too long"

Looks like the contents of kafka.properties and kafka.truststore may causing the arguments to be longer

**Comment by ekoutanov** [comment]
You can also pass in the truststore/keystore files by mounting them in a volume, then specifying their locations on the filesystem using the `KAFKA_TRUSTSTORE_FILE` and `KAFKA_KEYSTORE_FILE` environment variables. This way the argument list should be reasonably short.

**Comment by ekoutanov** [comment]
I wonder where specifically is the argument list too long...
Also, how big are your keystore and truststore files?

**Comment by ss1796** [comment]
The keystore is a very big file. Will try mounting the files in a volume.

**Comment by ss1796** [comment]
Even if I pass the files as environment variables, the command will have the convert the contents of the file to base64 encoded string and it will still cause the problem. My trust store is 100KB file.

**Comment by ekoutanov** [comment]
Fair enough.

I wonder if your keystore has more material in it than Kafdrop needs. A typical keystore containing a single 2048-bit RSA key, along with its signed certificate and a CA certificate weighs in at just under 4K. If there are other keys or certs that you've using across a bunch of apps, you might want to segregate the keystores.

**Comment by ss1796** [comment]
Removed all the trusted certs from the truststore and kept the couple that I need. Now I can deploy on Kubernetes. Still having issues connecting to the dashboard which I think I will be able to fix.
