### ISSUE TITLE
Possible error on overview Consumers with "Group ID"

### ISSUE THREAD

**Issue by piotrkosyoo** [obsidiandynamics/kafdrop#87]
Hi,
I created two group fist was test "Group ID"
And later second "azure-integration-consumer-email"
I made consume some message with a group  "Group ID" and switch later consumer to "azure-integration-consumer-email"

But now on the overview are wrong data but when I open a specific group is fine.

**Comment by piotrkosyoo** [comment]
Hi
Wrong topis on group the topis after open "Group Id is wrong" should be "streaming_emails_test" but is redirect to "streaming_emails"
![1](https://user-images.githubusercontent.com/6917040/75028312-52455f00-54a0-11ea-93b6-267a15ad61a4.png)

![3](https://user-images.githubusercontent.com/6917040/75028306-51143200-54a0-11ea-9087-34415d610911.png)
![2](https://user-images.githubusercontent.com/6917040/75028309-52455f00-54a0-11ea-843b-e0eee7ff9c6a.png)
Is a normal ?
Thanks for help

**Comment by ekoutanov** [comment]
I'm not sure what you mean by 'redirecting'.
