### ISSUE TITLE
InvalidProtocolBufferException error with ProtobufMessageDeserializer when data has mandatory fields

### ISSUE THREAD

**Issue by aruku773** [obsidiandynamics/kafdrop#89]
Hi 
InvalidProtocolBufferException error is thrown with ProtobufMessageDeserializer.
Verified the data and the reported missing fields are present in the data.
Any suggestions on how to resolve the issue ?

com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: creationTime, programId, userId, viewingSessionId
	at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:79)
	at com.google.protobuf.DynamicMessage$Builder.buildParsed(DynamicMessage.java:419)
	at com.google.protobuf.DynamicMessage$Builder.access$000(DynamicMessage.java:319)
	at com.google.protobuf.DynamicMessage.parseFrom(DynamicMessage.java:92)
	at kafdrop.util.ProtobufMessageDeserializer.deserializeMessage(ProtobufMessageDeserializer.java:86)
	at kafdrop.service.KafkaHighLevelConsumer.deserialize(KafkaHighLevelConsumer.java:193)
	at kafdrop.service.KafkaHighLevelConsumer.lambda$getLatestRecords$3(KafkaHighLevelConsumer.java:126)

**Comment by ekoutanov** [comment]
@ctrongduc and @AndreiIvanitckii, would either one of you mind taking a look? I'm not knowledgeable in protobuf.

**Comment by ctrongduc** [comment]
@aruku773 
Make sure there is no empty message in your topic. 
You could try to read just a few messages from the topic to ensure this is the problem with every message or just a few of them.

**Comment by aruku773** [comment]
@ctrongduc 
I have re-verified the data by consuming with other application and there are no empty messages in the topic.
Also tested with messages in other topics and getting the same exception.

**Comment by AndreiIvanitckii** [comment]
@aruku773
Required field... seems like you are using protobuf2.
Can you please provide a small, self-contained example which reproduces the problem with `.proto` files, `.desc` file and the proto message causing the problem.
And specify `protoc` version you use please.

**Comment by aruku773** [comment]
@AndreiIvanitckii 
Yes you are right. Iam using protobuf2 syntax and protoc version 2.6.1 (protoc-2.6.1).
Attaching .proto and .desc file now.
[proto_desc_files.zip](https://github.com/obsidiandynamics/kafdrop/files/4281191/proto_desc_files.zip)

Will create and send you the self-contained example to simulate.

**Comment by AndreiIvanitckii** [comment]
@aruku773 I tried your `.proto` file with `protoc-2.5.0` and everything works.
Does it work for you? If you resolved your problem can you please close the issue.

**Comment by aruku773** [comment]
I will check with protoc-2.5.0 at my end. Since working for you ,will be closing the issue.
