### ISSUE TITLE
Hope to be able to launch consumer monitoring

### ISSUE THREAD

**Issue by lifa1225** [obsidiandynamics/kafdrop#93]
Hope to be able to launch consumer monitoring

**Comment by ekoutanov** [comment]
What does that mean? Can you please be more specific.

**Comment by lifa1225** [comment]
like Kafka Eagle：
![Uploading image.png…]()

**Comment by lifa1225** [comment]
![image](https://user-images.githubusercontent.com/59470742/76373660-063d5a00-637c-11ea-98bc-58b52adc0c55.png)

**Comment by ekoutanov** [comment]
That already exists in the topic screen.

**Comment by lifa1225** [comment]
wow!thanks
