### ISSUE TITLE
Fails to build with dependency errors.

### ISSUE THREAD

**Issue by peter-snr** [obsidiandynamics/kafdrop#95]
1. Check out repo.
$  git clone https://github.com/obsidiandynamics/kafdrop.git

2. Execute build.
$ mvn clean package
[ERROR] Failed to execute goal on project kafdrop: Could not resolve dependencies for project com.obsidiandynamics.kafdrop:kafdrop:jar:3.24.0: Failed to collect dependencies for [com.google.protobuf:protobuf-java:jar:3.11.1 (compile), com.google.protobuf:protobuf-java-util:jar:3.11.1 (compile), org.apache.commons:commons-lang3:jar:3.9 (compile), org.springframework.boot:spring-boot-configuration-processor:jar:2.1.8.RELEASE (compile?), org.projectlombok:lombok:jar:1.18.8 (compile), org.apache.kafka:kafka-clients:jar:2.3.1 (compile), org.freemarker:freemarker:jar:2.3.28 (compile), io.confluent:kafka-avro-serializer:jar:5.2.2 (compile), org.apache.avro:avro:jar:1.9.1 (compile), org.springframework.boot:spring-boot-starter-web:jar:2.1.8.RELEASE (compile), org.springframework.boot:spring-boot-starter-undertow:jar:2.1.8.RELEASE (compile), io.undertow:undertow-core:jar:2.0.26.Final (compile), org.springframework.boot:spring-boot-starter-freemarker:jar:2.1.8.RELEASE (compile), org.springframework.boot:spring-boot-starter-log4j2:jar:2.1.8.RELEASE (compile), org.springframework.boot:spring-boot-starter-actuator:jar:2.1.8.RELEASE (compile), org.springframework:spring-context:jar:5.1.9.RELEASE (compile), org.springframework:spring-core:jar:5.1.9.RELEASE (compile), org.springframework:spring-beans:jar:5.1.9.RELEASE (compile), io.springfox:springfox-swagger2:jar:2.9.2 (compile), junit:junit:jar:4.12 (test)]: Failed to read artifact descriptor for io.confluent:kafka-avro-serializer:jar:5.2.2: Could not transfer artifact io.confluent:kafka-avro-serializer:pom:5.2.2 from/to confluent (https://packages.confluent.io/maven/): peer not authenticated 

Oops....

**Comment by ekoutanov** [comment]
Just did a clean checkout with an empty Maven cache, and it all worked. Also, we use Travis for CI which runs this sort of thing repeatedly from a clean slate, and it hasn't picked up an issue. Will close issue. Feel free to add any additional context that could help reproduce and reopen.

**Comment by Self-Perfection** [comment]
Could not build on arch linux with similar symptoms.
