### ISSUE TITLE
Helm Repository?

### ISSUE THREAD

**Issue by ParthKolekar** [obsidiandynamics/kafdrop#98]
Is the kafdrop chart hosted on a helm repository? If not, could you please consider hosting it on one? It helps as it eliminates the need to download the entire source code for deployment of this one chart and allows easier customization too.

**Comment by ekoutanov** [comment]
It's not hosted in a repo. Can you please clarify how that would enable for easier customisation, compared to checking out the repo and running Helm on a local chart?

**Comment by ParthKolekar** [comment]
We use the flux's helm operator : https://github.com/fluxcd/helm-operator

Most of the time, we do not run the helm commands from the command line,
but instead run it via the operator. The operator can pull a helm chart and
apply it, but it needs a chart from a helm hub.

**Comment by ekoutanov** [comment]
Interesting, I've not seen Flux before; I'll take a look.

**Comment by jvdgeest** [comment]
> It's not hosted in a repo. Can you please clarify how that would enable for easier customisation, compared to checking out the repo and running Helm on a local chart?

In automated deployments (like Terraform) it makes life a lot easier to have the chart hosted somewhere! Maybe GitHub pages could be an easy option, like https://argoproj.github.io/argo-helm?

**Comment by Tarasovych** [comment]
Having Helm repository would be nice

**Comment by arvin-pjr** [comment]
any plan adding this?
